In [27]:
!pip install requests
!pip install pandas

Requirement already satisfied: requests in .\mi_entorno\Lib\site-packages (2.34.2)
Requirement already satisfied: charset_normalizer<4,>=2 in .\mi_entorno\Lib\site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in .\mi_entorno\Lib\site-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in .\mi_entorno\Lib\site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in .\mi_entorno\Lib\site-packages (from requests) (2026.6.17)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in .\mi_entorno\Lib\site-packages (3.0.4)
Requirement already satisfied: numpy>=2.3.3 in .\mi_entorno\Lib\site-packages (from pandas) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in .\mi_entorno\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\mi_entorno\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\mi_entorno\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [29]:
import requests
import pandas as pd

BASE_URL = "https://www.fotmob.com/api/data/leagues"

ligas = {
    "Premier League": 47,
    "LaLiga": 87,
    "Serie A": 55,
    "Bundesliga": 54,
    "Ligue 1": 53
}

def obtener_clasificacion(id_liga, temporada="2025/2026", pais="ESP"):
    params = {
        "id": id_liga,
        "ccode3": pais,
        "season": temporada
    }

    r = requests.get(BASE_URL, params=params)
    data = r.json()

    # Extraer tabla
    tablas = data.get("table", [])
    for bloque in tablas:
        tabla_obj = bloque.get("data", {}).get("table", {})
        if isinstance(tabla_obj, dict) and "all" in tabla_obj:
            df = pd.DataFrame(tabla_obj["all"])
            return df

    print(f"⚠ No se encontró tabla 'all' para liga {id_liga}")
    return None


clasificaciones = {}

for nombre_liga, id_liga in ligas.items():
    print(f"\n🏆 {nombre_liga}")
    df = obtener_clasificacion(id_liga)
    clasificaciones[nombre_liga] = df

for liga, df in clasificaciones.items():
    print(f"\n==============================")
    print(f"📌 Clasificación: {liga}")
    print("==============================")
    if df is not None:
        display(df)
    else:
        print("No disponible")

🏆 Premier League

🏆 LaLiga

🏆 Serie A

🏆 Bundesliga

🏆 Ligue 1

==============================
📌 Clasificación: Premier League
==============================

,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,pts,idx,qualColor
0,Arsenal,Arsenal,9825,/teams/9825/overview/arsenal,None,None,38,26,7,5,71-27,44,85,1,#2AD572
1,Manchester City,Man City,8456,/teams/8456/overview/manchester-city,None,None,38,23,9,6,77-35,42,78,2,#2AD572
2,Manchester United,Man United,10260,/teams/10260/overview/manchester-united,None,None,38,20,11,7,69-50,19,71,3,#2AD572
3,Aston Villa,Aston Villa,10252,/teams/10252/overview/aston-villa,None,None,38,19,8,11,56-49,7,65,4,#2AD572
4,Liverpool,Liverpool,8650,/teams/8650/overview/liverpool,None,None,38,17,9,12,63-53,10,60,5,#2AD572
5,AFC Bournemouth,Bournemouth,8678,/teams/8678/overview/afc-bournemouth,None,None,38,13,18,7,58-54,4,57,6,#0046A7
6,Sunderland,Sunderland,8472,/teams/8472/overview/sunderland,None,None,38,14,12,12,42-48,-6,54,7,#0046A7
7,Brighton & Hove Albion,Brighton,10204,/teams/10204/overview/brighton-hove-albion,None,None,38,14,11,13,52-46,6,53,8,#02CCF0
8,Brentford,Brentford,9937,/teams/9937/overview/brentford,None,None,38,14,11,13,55-52,3,53,9,NaN
9,Chelsea,Chelsea,8455,/teams/8455/overview/chelsea,None,None,38,14,10,14,58-52,6,52,10,NaN
10,Fulham,Fulham,9879,/teams/9879/overview/fulham,None,None,38,15,7,16,47-51,-4,52,11,NaN
11,Newcastle United,Newcastle,10261,/teams/10261/overview/newcastle-united,None,None,38,14,7,17,53-55,-2,49,12,NaN
12,Everton,Everton,8668,/teams/8668/overview/everton,None,None,38,13,10,15,47-50,-3,49,13,NaN
13,Leeds United,Leeds,8463,/teams/8463/overview/leeds-united,None,None,38,11,14,13,49-56,-7,47,14,NaN
14,Crystal Palace,Crystal Palace,9826,/teams/9826/overview/crystal-palace,None,None,38,11,12,15,41-51,-10,45,15,#0046A7
15,Nottingham Forest,Nottm Forest,10203,/teams/10203/overview/nottingham-forest,None,None,38,11,11,16,48-51,-3,44,16,NaN
16,Tottenham Hotspur,Tottenham,8586,/teams/8586/overview/tottenham-hotspur,None,None,38,10,11,17,48-57,-9,41,17,NaN
17,West Ham United,West Ham,8654,/teams/8654/overview/west-ham-united,None,None,38,10,9,19,46-65,-19,39,18,#FF4646
18,Burnley,Burnley,8191,/teams/8191/overview/burnley,None,None,38,4,10,24,38-75,-37,22,19,#FF4646
19,Wolverhampton Wanderers,Wolves,8602,/teams/8602/overview/wolverhampton-wanderers,None,None,38,3,11,24,27-68,-41,20,20,#FF4646

==============================
📌 Clasificación: LaLiga
==============================

,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,pts,idx,qualColor
0,Barcelona,Barcelona,8634,/teams/8634/overview/barcelona,None,None,38,31,1,6,95-36,59,94,1,#2AD572
1,Real Madrid,Real Madrid,8633,/teams/8633/overview/real-madrid,None,None,38,27,5,6,77-35,42,86,2,#2AD572
2,Villarreal,Villarreal,10205,/teams/10205/overview/villarreal,None,None,38,22,6,10,72-46,26,72,3,#2AD572
3,Atletico Madrid,Atletico Madrid,9906,/teams/9906/overview/atletico-madrid,None,None,38,21,6,11,62-44,18,69,4,#2AD572
4,Real Betis,Real Betis,8603,/teams/8603/overview/real-betis,None,None,38,15,15,8,59-48,11,60,5,#2AD572
5,Celta Vigo,Celta Vigo,9910,/teams/9910/overview/celta-vigo,None,None,38,14,12,12,53-48,5,54,6,#0046A7
6,Getafe,Getafe,8305,/teams/8305/overview/getafe,None,None,38,15,6,17,32-38,-6,51,7,#02CCF0
7,Rayo Vallecano,Rayo Vallecano,8370,/teams/8370/overview/rayo-vallecano,None,None,38,12,14,12,41-44,-3,50,8,NaN
8,Valencia,Valencia,10267,/teams/10267/overview/valencia,None,None,38,13,10,15,46-55,-9,49,9,NaN
9,Real Sociedad,Real Sociedad,8560,/teams/8560/overview/real-sociedad,None,None,38,11,13,14,59-61,-2,46,10,#0046A7
10,Espanyol,Espanyol,8558,/teams/8558/overview/espanyol,None,None,38,12,10,16,43-55,-12,46,11,NaN
11,Athletic Club,Athletic Club,8315,/teams/8315/overview/athletic-club,None,None,38,13,6,19,43-58,-15,45,12,NaN
12,Sevilla,Sevilla,8302,/teams/8302/overview/sevilla,None,None,38,12,7,19,46-60,-14,43,13,NaN
13,Deportivo Alaves,Deportivo Alaves,9866,/teams/9866/overview/deportivo-alaves,None,None,38,11,10,17,44-56,-12,43,14,NaN
14,Elche,Elche,10268,/teams/10268/overview/elche,None,None,38,10,13,15,49-57,-8,43,15,NaN
15,Levante,Levante,8581,/teams/8581/overview/levante,None,None,38,11,9,18,47-61,-14,42,16,NaN
16,Osasuna,Osasuna,8371,/teams/8371/overview/osasuna,None,None,38,11,9,18,44-50,-6,42,17,NaN
17,Mallorca,Mallorca,8661,/teams/8661/overview/mallorca,None,None,38,11,9,18,47-57,-10,42,18,#FF4646
18,Girona,Girona,7732,/teams/7732/overview/girona,None,None,38,9,14,15,39-55,-16,41,19,#FF4646
19,Real Oviedo,Real Oviedo,8670,/teams/8670/overview/real-oviedo,None,None,38,6,11,21,26-60,-34,29,20,#FF4646

==============================
📌 Clasificación: Serie A
==============================

,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,pts,idx,qualColor
0,Inter,Inter,8636,/teams/8636/overview/inter,None,None,38,27,6,5,89-35,54,87,1,#2AD572
1,Napoli,Napoli,9875,/teams/9875/overview/napoli,None,None,38,23,7,8,58-36,22,76,2,#2AD572
2,Roma,Roma,8686,/teams/8686/overview/roma,None,None,38,23,4,11,59-31,28,73,3,#2AD572
3,Como,Como,10171,/teams/10171/overview/como,None,None,38,20,11,7,65-29,36,71,4,#2AD572
4,Milan,Milan,8564,/teams/8564/overview/milan,None,None,38,20,10,8,53-35,18,70,5,#0046A7
5,Juventus,Juventus,9885,/teams/9885/overview/juventus,None,None,38,19,12,7,61-34,27,69,6,#0046A7
6,Atalanta,Atalanta,8524,/teams/8524/overview/atalanta,None,None,38,15,14,9,51-36,15,59,7,#02CCF0
7,Bologna,Bologna,9857,/teams/9857/overview/bologna,None,None,38,16,8,14,49-46,3,56,8,NaN
8,Lazio,Lazio,8543,/teams/8543/overview/lazio,None,None,38,14,12,12,41-40,1,54,9,NaN
9,Udinese,Udinese,8600,/teams/8600/overview/udinese,None,None,38,14,8,16,45-48,-3,50,10,NaN
10,Sassuolo,Sassuolo,7943,/teams/7943/overview/sassuolo,None,None,38,14,7,17,46-50,-4,49,11,NaN
11,Torino,Torino,9804,/teams/9804/overview/torino,None,None,38,12,9,17,44-63,-19,45,12,NaN
12,Parma,Parma,10167,/teams/10167/overview/parma,None,None,38,11,12,15,28-46,-18,45,13,NaN
13,Cagliari,Cagliari,8529,/teams/8529/overview/cagliari,None,None,38,11,10,17,40-53,-13,43,14,NaN
14,Fiorentina,Fiorentina,8535,/teams/8535/overview/fiorentina,None,None,38,9,15,14,41-50,-9,42,15,NaN
15,Genoa,Genoa,10233,/teams/10233/overview/genoa,None,None,38,10,11,17,41-51,-10,41,16,NaN
16,Lecce,Lecce,9888,/teams/9888/overview/lecce,None,None,38,10,8,20,28-50,-22,38,17,NaN
17,Cremonese,Cremonese,7801,/teams/7801/overview/cremonese,None,None,38,8,10,20,32-57,-25,34,18,#FF4646
18,Hellas Verona,Hellas Verona,9876,/teams/9876/overview/hellas-verona,None,None,38,3,12,23,25-61,-36,21,19,#FF4646
19,Pisa,Pisa,6479,/teams/6479/overview/pisa,None,None,38,2,12,24,26-71,-45,18,20,#FF4646

==============================
📌 Clasificación: Bundesliga
==============================

,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,pts,idx,qualColor
0,Bayern München,Bayern München,9823,/teams/9823/overview/bayern-munchen,None,None,34,28,5,1,122-36,86,89,1,#2AD572
1,Borussia Dortmund,Dortmund,9789,/teams/9789/overview/borussia-dortmund,None,None,34,22,7,5,70-34,36,73,2,#2AD572
2,RB Leipzig,RB Leipzig,178475,/teams/178475/overview/rb-leipzig,None,None,34,20,5,9,66-47,19,65,3,#2AD572
3,VfB Stuttgart,VfB Stuttgart,10269,/teams/10269/overview/vfb-stuttgart,None,None,34,18,8,8,71-49,22,62,4,#2AD572
4,Hoffenheim,Hoffenheim,8226,/teams/8226/overview/hoffenheim,None,None,34,18,7,9,65-52,13,61,5,#0046A7
5,Bayer Leverkusen,Leverkusen,8178,/teams/8178/overview/bayer-leverkusen,None,None,34,17,8,9,68-47,21,59,6,#0046A7
6,Freiburg,Freiburg,8358,/teams/8358/overview/freiburg,None,None,34,13,8,13,51-57,-6,47,7,#02CCF0
7,Eintracht Frankfurt,Frankfurt,9810,/teams/9810/overview/eintracht-frankfurt,None,None,34,11,11,12,61-65,-4,44,8,NaN
8,Augsburg,Augsburg,8406,/teams/8406/overview/augsburg,None,None,34,12,7,15,45-61,-16,43,9,NaN
9,Mainz 05,Mainz,9905,/teams/9905/overview/mainz-05,None,None,34,10,10,14,44-53,-9,40,10,NaN
10,Union Berlin,Union Berlin,8149,/teams/8149/overview/union-berlin,None,None,34,10,9,15,44-58,-14,39,11,NaN
11,Borussia Mönchengladbach,M'gladbach,9788,/teams/9788/overview/borussia-monchengladbach,None,None,34,9,11,14,42-53,-11,38,12,NaN
12,Hamburger SV,Hamburger SV,9790,/teams/9790/overview/hamburger-sv,None,None,34,9,11,14,40-54,-14,38,13,NaN
13,1. FC Köln,Köln,8722,/teams/8722/overview/1-fc-koln,None,None,34,7,11,16,49-63,-14,32,14,NaN
14,Werder Bremen,Werder Bremen,8697,/teams/8697/overview/werder-bremen,None,None,34,8,8,18,37-60,-23,32,15,NaN
15,Wolfsburg,Wolfsburg,8721,/teams/8721/overview/wolfsburg,None,None,34,7,8,19,45-69,-24,29,16,#FFA72F
16,FC Heidenheim,FC Heidenheim,94937,/teams/94937/overview/fc-heidenheim,None,None,34,6,8,20,41-72,-31,26,17,#FF4646
17,St. Pauli,St. Pauli,8152,/teams/8152/overview/st-pauli,None,None,34,6,8,20,29-60,-31,26,18,#FF4646

==============================
📌 Clasificación: Ligue 1
==============================

,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,pts,idx,qualColor
0,Paris Saint-Germain,PSG,9847,/teams/9847/overview/paris-saint-germain,None,None,34,24,4,6,74-29,45,76,1,#2AD572
1,Lens,Lens,8588,/teams/8588/overview/lens,None,None,34,22,4,8,66-35,31,70,2,#2AD572
2,Lille,Lille,8639,/teams/8639/overview/lille,None,None,34,18,7,9,52-37,15,61,3,#2AD572
3,Lyon,Lyon,9748,/teams/9748/overview/lyon,None,None,34,18,6,10,53-40,13,60,4,#FFD908
4,Marseille,Marseille,8592,/teams/8592/overview/marseille,None,None,34,18,5,11,63-45,18,59,5,#0046A7
5,Rennes,Rennes,9851,/teams/9851/overview/rennes,None,None,34,17,8,9,59-50,9,59,6,#0046A7
6,Monaco,Monaco,9829,/teams/9829/overview/monaco,None,None,34,16,6,12,60-54,6,54,7,#02CCF0
7,Strasbourg,Strasbourg,9848,/teams/9848/overview/strasbourg,None,None,34,15,8,11,58-47,11,53,8,NaN
8,Toulouse,Toulouse,9941,/teams/9941/overview/toulouse,None,None,34,12,9,13,47-46,1,45,9,NaN
9,Lorient,Lorient,8689,/teams/8689/overview/lorient,None,None,34,11,12,11,48-51,-3,45,10,NaN
10,Paris FC,Paris FC,6379,/teams/6379/overview/paris-fc,None,None,34,11,11,12,47-50,-3,44,11,NaN
11,Brest,Brest,8521,/teams/8521/overview/brest,None,None,34,10,9,15,43-55,-12,39,12,NaN
12,Angers,Angers,8121,/teams/8121/overview/angers,None,None,34,9,9,16,29-48,-19,36,13,NaN
13,Le Havre,Le Havre,9746,/teams/9746/overview/le-havre,None,None,34,7,14,13,32-44,-12,35,14,NaN
14,Auxerre,Auxerre,8583,/teams/8583/overview/auxerre,None,None,34,8,10,16,34-44,-10,34,15,NaN
15,Nice,Nice,9831,/teams/9831/overview/nice,None,None,34,7,11,16,37-60,-23,32,16,#FFA72F
16,Nantes,Nantes,9830,/teams/9830/overview/nantes,None,None,34,5,9,20,29-52,-23,24,17,#FF4646
17,Metz,Metz,8550,/teams/8550/overview/metz,None,None,34,3,8,23,32-76,-44,17,18,#FF4646

Crear funcion para extraer todos los tipos, no solo la clasificacion

In [32]:
import requests
import pandas as pd

BASE_URL = "https://www.fotmob.com/api/data/leagues"

ligas = {
    "Premier League": 47,
    "LaLiga": 87,
    "Serie A": 55,
    "Bundesliga": 54,
    "Ligue 1": 53
}

# -----------------------------
# FUNCIÓN 1: Extraer todas las pestañas
# -----------------------------
def extraer_tablas(data):
    """
    Devuelve un diccionario con los DataFrames de:
    - all
    - home
    - away
    - last5 (form)
    - xG (desde stats)
    Incluye la URL del logo del equipo.
    """
    tablas = data.get("table", [])
    resultados = {"all": None, "home": None, "away": None, "last5": None, "xG": None}

    # ALL / HOME / AWAY / LAST5 desde table
    for bloque in tablas:
        tabla_obj = bloque.get("data", {}).get("table", {})
        if not isinstance(tabla_obj, dict):
            continue

        for tipo in ["all", "home", "away", "form"]:
            if tipo in tabla_obj:
                df = pd.DataFrame(tabla_obj[tipo])
                # Añadir logo si existe
                if "team" in df.columns:
                    df["logoUrl"] = df["team"].apply(lambda t: t.get("logo") if isinstance(t, dict) else None)
                    df["name"] = df["team"].apply(lambda t: t.get("name") if isinstance(t, dict) else None)
                    df["shortName"] = df["team"].apply(lambda t: t.get("shortName") if isinstance(t, dict) else None)
                resultados["last5" if tipo == "form" else tipo] = df

    # xG desde stats (solo temporada pedida)
    stats = data.get("stats", {})
    teams_stats = stats.get("teams", [])
    if teams_stats:
        xg_df = pd.DataFrame(teams_stats)
        # Filtrar columnas relevantes
        columnas_xg = [c for c in xg_df.columns if "xG" in c or "xg" in c.lower()] + ["name", "shortName", "id", "pageUrl"]
        columnas_xg = list(dict.fromkeys(columnas_xg))
        xg_df = xg_df[[c for c in columnas_xg if c in xg_df.columns]]
        resultados["xG"] = xg_df

    return resultados


# -----------------------------
# FUNCIÓN 2: Preparar los DataFrames
# -----------------------------
def preparar_tablas(tablas_dict, nombre_liga, temporada):
    """
    Limpia y añade metadatos a los DataFrames.
    Devuelve un diccionario con los DataFrames preparados.
    """
    preparados = {}
    for tipo, df in tablas_dict.items():
        if df is not None:
            df = df.copy()
            df["Liga"] = nombre_liga
            df["Tipo"] = tipo
            df["Temporada"] = temporada
            columnas = ["Liga", "Tipo", "Temporada"] + [c for c in df.columns if c not in ["Liga", "Tipo", "Temporada"]]
            df = df[columnas]
            preparados[tipo] = df
    return preparados


# -----------------------------
# FUNCIÓN 3: Obtener y preparar datos de liga
# -----------------------------
def obtener_clasificacion(id_liga, nombre_liga, season_in=2025, season_out=2026, pais="ESP"):
    temporada = f"{season_in}/{season_out}"
    params = {"id": id_liga, "ccode3": pais, "season": temporada}
    r = requests.get(BASE_URL, params=params)
    data = r.json()

    tablas = extraer_tablas(data)
    tablas_preparadas = preparar_tablas(tablas, nombre_liga, temporada)
    return tablas_preparadas


# -----------------------------
# PROCESO PRINCIPAL
# -----------------------------
clasificaciones = {}

season_in = 2025
season_out = 2026

for nombre_liga, id_liga in ligas.items():
    print(f"\n🏆 {nombre_liga}")
    tablas = obtener_clasificacion(id_liga, nombre_liga, season_in, season_out)
    clasificaciones[nombre_liga] = tablas

    for tipo, df in tablas.items():
        print(f"\n📌 {nombre_liga} — {tipo.upper()}")
        if df is not None:
            display(df.head())
        else:
            print("No disponible")

🏆 Premier League

📌 Premier League — ALL

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,pts,idx,qualColor
0,Premier League,all,2025/2026,Arsenal,Arsenal,9825,/teams/9825/overview/arsenal,None,None,38,26,7,5,71-27,44,85,1,#2AD572
1,Premier League,all,2025/2026,Manchester City,Man City,8456,/teams/8456/overview/manchester-city,None,None,38,23,9,6,77-35,42,78,2,#2AD572
2,Premier League,all,2025/2026,Manchester United,Man United,10260,/teams/10260/overview/manchester-united,None,None,38,20,11,7,69-50,19,71,3,#2AD572
3,Premier League,all,2025/2026,Aston Villa,Aston Villa,10252,/teams/10252/overview/aston-villa,None,None,38,19,8,11,56-49,7,65,4,#2AD572
4,Premier League,all,2025/2026,Liverpool,Liverpool,8650,/teams/8650/overview/liverpool,None,None,38,17,9,12,63-53,10,60,5,#2AD572

📌 Premier League — HOME

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,idx,qualColor
0,Premier League,home,2025/2026,Arsenal,Arsenal,9825,/teams/9825/overview/arsenal,None,None,19,15,2,2,41-11,30,41,47,1,#2AD572
1,Premier League,home,2025/2026,Manchester City,Man City,8456,/teams/8456/overview/manchester-city,None,None,19,14,3,2,45-14,31,45,45,2,#2AD572
2,Premier League,home,2025/2026,Manchester United,Man United,10260,/teams/10260/overview/manchester-united,None,None,19,13,3,3,39-24,15,39,42,3,#2AD572
3,Premier League,home,2025/2026,Aston Villa,Aston Villa,10252,/teams/10252/overview/aston-villa,None,None,19,12,2,5,32-22,10,32,38,4,#2AD572
4,Premier League,home,2025/2026,Liverpool,Liverpool,8650,/teams/8650/overview/liverpool,None,None,19,10,6,3,34-20,14,34,36,5,#2AD572

📌 Premier League — AWAY

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,idx,qualColor
0,Premier League,away,2025/2026,Arsenal,Arsenal,9825,/teams/9825/overview/arsenal,None,None,19,11,5,3,30-16,14,30,38,1,#2AD572
1,Premier League,away,2025/2026,Manchester City,Man City,8456,/teams/8456/overview/manchester-city,None,None,19,9,6,4,32-21,11,32,33,2,#2AD572
2,Premier League,away,2025/2026,Manchester United,Man United,10260,/teams/10260/overview/manchester-united,None,None,19,7,8,4,30-26,4,30,29,3,#2AD572
3,Premier League,away,2025/2026,Aston Villa,Aston Villa,10252,/teams/10252/overview/aston-villa,None,None,19,7,6,6,24-27,-3,24,27,4,#2AD572
4,Premier League,away,2025/2026,Chelsea,Chelsea,8455,/teams/8455/overview/chelsea,None,None,19,7,5,7,32-27,5,32,26,5,#2AD572

📌 Premier League — LAST5

,Liga,Tipo,Temporada,name,shortName,featuredInMatch,id,pageUrl,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,ongoing,idx,qualColor
0,Premier League,last5,2025/2026,Arsenal,Arsenal,False,9825,/teams/9825/overview/arsenal,5,5,0,0,8-1,7,8,15,None,1,#2AD572
1,Premier League,last5,2025/2026,Manchester United,Man United,False,10260,/teams/10260/overview/manchester-united,5,4,1,0,11-5,6,11,13,None,2,#2AD572
2,Premier League,last5,2025/2026,Tottenham Hotspur,Tottenham,False,8586,/teams/8586/overview/tottenham-hotspur,5,3,1,1,6-4,2,6,10,None,3,#2AD572
3,Premier League,last5,2025/2026,AFC Bournemouth,Bournemouth,False,8678,/teams/8678/overview/afc-bournemouth,5,2,3,0,8-4,4,8,9,None,4,#2AD572
4,Premier League,last5,2025/2026,Nottingham Forest,Nottm Forest,False,10203,/teams/10203/overview/nottingham-forest,5,2,2,1,12-6,6,12,8,None,5,#2AD572

📌 Premier League — XG

             Liga Tipo  Temporada                        name
0  Premier League   xG  2025/2026                 rating_team
1  Premier League   xG  2025/2026            goals_team_match
2  Premier League   xG  2025/2026   goals_conceded_team_match
3  Premier League   xG  2025/2026  possession_percentage_team
4  Premier League   xG  2025/2026            clean_sheet_team

🏆 LaLiga

📌 LaLiga — ALL

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,pts,idx,qualColor
0,LaLiga,all,2025/2026,Barcelona,Barcelona,8634,/teams/8634/overview/barcelona,None,None,38,31,1,6,95-36,59,94,1,#2AD572
1,LaLiga,all,2025/2026,Real Madrid,Real Madrid,8633,/teams/8633/overview/real-madrid,None,None,38,27,5,6,77-35,42,86,2,#2AD572
2,LaLiga,all,2025/2026,Villarreal,Villarreal,10205,/teams/10205/overview/villarreal,None,None,38,22,6,10,72-46,26,72,3,#2AD572
3,LaLiga,all,2025/2026,Atletico Madrid,Atletico Madrid,9906,/teams/9906/overview/atletico-madrid,None,None,38,21,6,11,62-44,18,69,4,#2AD572
4,LaLiga,all,2025/2026,Real Betis,Real Betis,8603,/teams/8603/overview/real-betis,None,None,38,15,15,8,59-48,11,60,5,#2AD572

📌 LaLiga — HOME

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,idx,qualColor
0,LaLiga,home,2025/2026,Barcelona,Barcelona,8634,/teams/8634/overview/barcelona,None,None,19,19,0,0,57-10,47,57,57,1,#2AD572
1,LaLiga,home,2025/2026,Real Madrid,Real Madrid,8633,/teams/8633/overview/real-madrid,None,None,19,16,1,2,45-16,29,45,49,2,#2AD572
2,LaLiga,home,2025/2026,Villarreal,Villarreal,10205,/teams/10205/overview/villarreal,None,None,19,15,1,3,48-19,29,48,46,3,#2AD572
3,LaLiga,home,2025/2026,Atletico Madrid,Atletico Madrid,9906,/teams/9906/overview/atletico-madrid,None,None,19,15,1,3,39-17,22,39,46,4,#2AD572
4,LaLiga,home,2025/2026,Real Betis,Real Betis,8603,/teams/8603/overview/real-betis,None,None,19,10,6,3,34-19,15,34,36,5,#2AD572

📌 LaLiga — AWAY

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,idx,qualColor
0,LaLiga,away,2025/2026,Real Madrid,Real Madrid,8633,/teams/8633/overview/real-madrid,None,None,19,11,4,4,32-19,13,32,37,1,#2AD572
1,LaLiga,away,2025/2026,Barcelona,Barcelona,8634,/teams/8634/overview/barcelona,None,None,19,12,1,6,38-26,12,38,37,2,#2AD572
2,LaLiga,away,2025/2026,Celta Vigo,Celta Vigo,9910,/teams/9910/overview/celta-vigo,None,None,19,8,7,4,24-20,4,24,31,3,#2AD572
3,LaLiga,away,2025/2026,Villarreal,Villarreal,10205,/teams/10205/overview/villarreal,None,None,19,7,5,7,24-27,-3,24,26,4,#2AD572
4,LaLiga,away,2025/2026,Real Betis,Real Betis,8603,/teams/8603/overview/real-betis,None,None,19,5,9,5,25-29,-4,25,24,5,#2AD572

📌 LaLiga — LAST5

,Liga,Tipo,Temporada,name,shortName,featuredInMatch,id,pageUrl,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,ongoing,idx,qualColor
0,LaLiga,last5,2025/2026,Real Madrid,Real Madrid,False,8633,/teams/8633/overview/real-madrid,5,4,0,1,9-4,5,9,12,None,1,#2AD572
1,LaLiga,last5,2025/2026,Rayo Vallecano,Rayo Vallecano,False,8370,/teams/8370/overview/rayo-vallecano,5,3,2,0,8-3,5,8,11,None,2,#2AD572
2,LaLiga,last5,2025/2026,Real Betis,Real Betis,False,8603,/teams/8603/overview/real-betis,5,3,1,1,10-7,3,10,10,None,3,#2AD572
3,LaLiga,last5,2025/2026,Celta Vigo,Celta Vigo,False,9910,/teams/9910/overview/celta-vigo,5,3,1,1,8-5,3,8,10,None,4,#2AD572
4,LaLiga,last5,2025/2026,Valencia,Valencia,False,10267,/teams/10267/overview/valencia,5,3,1,1,9-7,2,9,10,None,5,#2AD572

📌 LaLiga — XG

     Liga Tipo  Temporada                        name
0  LaLiga   xG  2025/2026                 rating_team
1  LaLiga   xG  2025/2026            goals_team_match
2  LaLiga   xG  2025/2026   goals_conceded_team_match
3  LaLiga   xG  2025/2026  possession_percentage_team
4  LaLiga   xG  2025/2026            clean_sheet_team

🏆 Serie A

📌 Serie A — ALL

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,pts,idx,qualColor
0,Serie A,all,2025/2026,Inter,Inter,8636,/teams/8636/overview/inter,None,None,38,27,6,5,89-35,54,87,1,#2AD572
1,Serie A,all,2025/2026,Napoli,Napoli,9875,/teams/9875/overview/napoli,None,None,38,23,7,8,58-36,22,76,2,#2AD572
2,Serie A,all,2025/2026,Roma,Roma,8686,/teams/8686/overview/roma,None,None,38,23,4,11,59-31,28,73,3,#2AD572
3,Serie A,all,2025/2026,Como,Como,10171,/teams/10171/overview/como,None,None,38,20,11,7,65-29,36,71,4,#2AD572
4,Serie A,all,2025/2026,Milan,Milan,8564,/teams/8564/overview/milan,None,None,38,20,10,8,53-35,18,70,5,#0046A7

📌 Serie A — HOME

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,idx,qualColor
0,Serie A,home,2025/2026,Inter,Inter,8636,/teams/8636/overview/inter,None,None,19,14,3,2,50-16,34,50,45,1,#2AD572
1,Serie A,home,2025/2026,Napoli,Napoli,9875,/teams/9875/overview/napoli,None,None,19,13,4,2,33-18,15,33,43,2,#2AD572
2,Serie A,home,2025/2026,Roma,Roma,8686,/teams/8686/overview/roma,None,None,19,13,3,3,33-10,23,33,42,3,#2AD572
3,Serie A,home,2025/2026,Juventus,Juventus,9885,/teams/9885/overview/juventus,None,None,19,10,7,2,35-16,19,35,37,4,#2AD572
4,Serie A,home,2025/2026,Como,Como,10171,/teams/10171/overview/como,None,None,19,10,6,3,35-15,20,35,36,5,#0046A7

📌 Serie A — AWAY

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,idx,qualColor
0,Serie A,away,2025/2026,Inter,Inter,8636,/teams/8636/overview/inter,None,None,19,13,3,3,39-19,20,39,42,1,#2AD572
1,Serie A,away,2025/2026,Milan,Milan,8564,/teams/8564/overview/milan,None,None,19,11,5,3,28-14,14,28,38,2,#2AD572
2,Serie A,away,2025/2026,Como,Como,10171,/teams/10171/overview/como,None,None,19,10,5,4,30-14,16,30,35,3,#2AD572
3,Serie A,away,2025/2026,Bologna,Bologna,9857,/teams/9857/overview/bologna,None,None,19,10,4,5,30-23,7,30,34,4,#2AD572
4,Serie A,away,2025/2026,Napoli,Napoli,9875,/teams/9875/overview/napoli,None,None,19,10,3,6,25-18,7,25,33,5,#0046A7

📌 Serie A — LAST5

,Liga,Tipo,Temporada,name,shortName,featuredInMatch,id,pageUrl,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,ongoing,idx,qualColor
0,Serie A,last5,2025/2026,Roma,Roma,False,8686,/teams/8686/overview/roma,5,5,0,0,13-2,11,13,15,None,1,#2AD572
1,Serie A,last5,2025/2026,Como,Como,False,10171,/teams/10171/overview/como,5,4,1,0,8-1,7,8,13,None,2,#2AD572
2,Serie A,last5,2025/2026,Napoli,Napoli,False,9875,/teams/9875/overview/napoli,5,3,1,1,10-3,7,10,10,None,3,#2AD572
3,Serie A,last5,2025/2026,Lecce,Lecce,False,9888,/teams/9888/overview/lecce,5,3,1,1,6-4,2,6,10,None,4,#2AD572
4,Serie A,last5,2025/2026,Cagliari,Cagliari,False,8529,/teams/8529/overview/cagliari,5,3,1,1,7-6,1,7,10,None,5,#0046A7

📌 Serie A — XG

      Liga Tipo  Temporada                        name
0  Serie A   xG  2025/2026                 rating_team
1  Serie A   xG  2025/2026            goals_team_match
2  Serie A   xG  2025/2026   goals_conceded_team_match
3  Serie A   xG  2025/2026  possession_percentage_team
4  Serie A   xG  2025/2026            clean_sheet_team

🏆 Bundesliga

📌 Bundesliga — ALL

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,pts,idx,qualColor
0,Bundesliga,all,2025/2026,Bayern München,Bayern München,9823,/teams/9823/overview/bayern-munchen,None,None,34,28,5,1,122-36,86,89,1,#2AD572
1,Bundesliga,all,2025/2026,Borussia Dortmund,Dortmund,9789,/teams/9789/overview/borussia-dortmund,None,None,34,22,7,5,70-34,36,73,2,#2AD572
2,Bundesliga,all,2025/2026,RB Leipzig,RB Leipzig,178475,/teams/178475/overview/rb-leipzig,None,None,34,20,5,9,66-47,19,65,3,#2AD572
3,Bundesliga,all,2025/2026,VfB Stuttgart,VfB Stuttgart,10269,/teams/10269/overview/vfb-stuttgart,None,None,34,18,8,8,71-49,22,62,4,#2AD572
4,Bundesliga,all,2025/2026,Hoffenheim,Hoffenheim,8226,/teams/8226/overview/hoffenheim,None,None,34,18,7,9,65-52,13,61,5,#0046A7

📌 Bundesliga — HOME

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,idx,qualColor
0,Bundesliga,home,2025/2026,Bayern München,Bayern München,9823,/teams/9823/overview/bayern-munchen,None,None,17,14,2,1,68-19,49,68,44,1,#2AD572
1,Bundesliga,home,2025/2026,Borussia Dortmund,Dortmund,9789,/teams/9789/overview/borussia-dortmund,None,None,17,13,2,2,40-16,24,40,41,2,#2AD572
2,Bundesliga,home,2025/2026,VfB Stuttgart,VfB Stuttgart,10269,/teams/10269/overview/vfb-stuttgart,None,None,17,12,3,2,30-16,14,30,39,3,#2AD572
3,Bundesliga,home,2025/2026,RB Leipzig,RB Leipzig,178475,/teams/178475/overview/rb-leipzig,None,None,17,12,2,3,40-20,20,40,38,4,#2AD572
4,Bundesliga,home,2025/2026,Hoffenheim,Hoffenheim,8226,/teams/8226/overview/hoffenheim,None,None,17,10,2,5,35-21,14,35,32,5,#0046A7

📌 Bundesliga — AWAY

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,idx,qualColor
0,Bundesliga,away,2025/2026,Bayern München,Bayern München,9823,/teams/9823/overview/bayern-munchen,None,None,17,14,3,0,54-17,37,54,45,1,#2AD572
1,Bundesliga,away,2025/2026,Borussia Dortmund,Dortmund,9789,/teams/9789/overview/borussia-dortmund,None,None,17,9,5,3,30-18,12,30,32,2,#2AD572
2,Bundesliga,away,2025/2026,Hoffenheim,Hoffenheim,8226,/teams/8226/overview/hoffenheim,None,None,17,8,5,4,30-31,-1,30,29,3,#2AD572
3,Bundesliga,away,2025/2026,Bayer Leverkusen,Leverkusen,8178,/teams/8178/overview/bayer-leverkusen,None,None,17,8,4,5,30-28,2,30,28,4,#2AD572
4,Bundesliga,away,2025/2026,RB Leipzig,RB Leipzig,178475,/teams/178475/overview/rb-leipzig,None,None,17,8,3,6,26-27,-1,26,27,5,#0046A7

📌 Bundesliga — LAST5

,Liga,Tipo,Temporada,name,shortName,featuredInMatch,id,pageUrl,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,ongoing,idx,qualColor
0,Bundesliga,last5,2025/2026,Bayern München,Bayern München,False,9823,/teams/9823/overview/bayern-munchen,5,4,1,0,17-9,8,17,13,None,1,#2AD572
1,Bundesliga,last5,2025/2026,Augsburg,Augsburg,False,8406,/teams/8406/overview/augsburg,5,3,1,1,9-8,1,9,10,None,2,#2AD572
2,Bundesliga,last5,2025/2026,Hoffenheim,Hoffenheim,False,8226,/teams/8226/overview/hoffenheim,5,3,1,1,8-9,-1,8,10,None,3,#2AD572
3,Bundesliga,last5,2025/2026,Borussia Dortmund,Dortmund,False,9789,/teams/9789/overview/borussia-dortmund,5,3,0,2,10-5,5,10,9,None,4,#2AD572
4,Bundesliga,last5,2025/2026,RB Leipzig,RB Leipzig,False,178475,/teams/178475/overview/rb-leipzig,5,3,0,2,10-11,-1,10,9,None,5,#0046A7

📌 Bundesliga — XG

         Liga Tipo  Temporada                        name
0  Bundesliga   xG  2025/2026                 rating_team
1  Bundesliga   xG  2025/2026            goals_team_match
2  Bundesliga   xG  2025/2026   goals_conceded_team_match
3  Bundesliga   xG  2025/2026  possession_percentage_team
4  Bundesliga   xG  2025/2026            clean_sheet_team

🏆 Ligue 1

📌 Ligue 1 — ALL

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,pts,idx,qualColor
0,Ligue 1,all,2025/2026,Paris Saint-Germain,PSG,9847,/teams/9847/overview/paris-saint-germain,None,None,34,24,4,6,74-29,45,76,1,#2AD572
1,Ligue 1,all,2025/2026,Lens,Lens,8588,/teams/8588/overview/lens,None,None,34,22,4,8,66-35,31,70,2,#2AD572
2,Ligue 1,all,2025/2026,Lille,Lille,8639,/teams/8639/overview/lille,None,None,34,18,7,9,52-37,15,61,3,#2AD572
3,Ligue 1,all,2025/2026,Lyon,Lyon,9748,/teams/9748/overview/lyon,None,None,34,18,6,10,53-40,13,60,4,#FFD908
4,Ligue 1,all,2025/2026,Marseille,Marseille,8592,/teams/8592/overview/marseille,None,None,34,18,5,11,63-45,18,59,5,#0046A7

📌 Ligue 1 — HOME

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,idx,qualColor
0,Ligue 1,home,2025/2026,Lens,Lens,8588,/teams/8588/overview/lens,None,None,17,14,0,3,35-13,22,35,42,1,#2AD572
1,Ligue 1,home,2025/2026,Paris Saint-Germain,PSG,9847,/teams/9847/overview/paris-saint-germain,None,None,17,13,2,2,41-12,29,41,41,2,#2AD572
2,Ligue 1,home,2025/2026,Marseille,Marseille,8592,/teams/8592/overview/marseille,None,None,17,11,4,2,41-20,21,41,37,3,#2AD572
3,Ligue 1,home,2025/2026,Lyon,Lyon,9748,/teams/9748/overview/lyon,None,None,17,12,1,4,30-18,12,30,37,4,#FFD908
4,Ligue 1,home,2025/2026,Rennes,Rennes,9851,/teams/9851/overview/rennes,None,None,17,10,4,3,30-17,13,30,34,5,#0046A7

📌 Ligue 1 — AWAY

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,idx,qualColor
0,Ligue 1,away,2025/2026,Paris Saint-Germain,PSG,9847,/teams/9847/overview/paris-saint-germain,None,None,17,11,2,4,33-17,16,33,35,1,#2AD572
1,Ligue 1,away,2025/2026,Lille,Lille,8639,/teams/8639/overview/lille,None,None,17,10,2,5,28-20,8,28,32,2,#2AD572
2,Ligue 1,away,2025/2026,Lens,Lens,8588,/teams/8588/overview/lens,None,None,17,8,4,5,31-22,9,31,28,3,#2AD572
3,Ligue 1,away,2025/2026,Rennes,Rennes,9851,/teams/9851/overview/rennes,None,None,17,7,4,6,29-33,-4,29,25,4,#FFD908
4,Ligue 1,away,2025/2026,Lyon,Lyon,9748,/teams/9748/overview/lyon,None,None,17,6,5,6,23-22,1,23,23,5,#0046A7

📌 Ligue 1 — LAST5

,Liga,Tipo,Temporada,name,shortName,featuredInMatch,id,pageUrl,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,ongoing,idx,qualColor
0,Ligue 1,last5,2025/2026,Paris Saint-Germain,PSG,False,9847,/teams/9847/overview/paris-saint-germain,5,3,1,1,9-4,5,9,10,None,1,#2AD572
1,Ligue 1,last5,2025/2026,Auxerre,Auxerre,False,8583,/teams/8583/overview/auxerre,5,3,1,1,11-7,4,11,10,None,2,#2AD572
2,Ligue 1,last5,2025/2026,Strasbourg,Strasbourg,False,9848,/teams/9848/overview/strasbourg,5,3,1,1,12-10,2,12,10,None,3,#2AD572
3,Ligue 1,last5,2025/2026,Paris FC,Paris FC,False,6379,/teams/6379/overview/paris-fc,5,3,0,2,10-5,5,10,9,None,4,#FFD908
4,Ligue 1,last5,2025/2026,Rennes,Rennes,False,9851,/teams/9851/overview/rennes,5,3,0,2,10-9,1,10,9,None,5,#0046A7

📌 Ligue 1 — XG

      Liga Tipo  Temporada                        name
0  Ligue 1   xG  2025/2026                 rating_team
1  Ligue 1   xG  2025/2026            goals_team_match
2  Ligue 1   xG  2025/2026   goals_conceded_team_match
3  Ligue 1   xG  2025/2026  possession_percentage_team
4  Ligue 1   xG  2025/2026            clean_sheet_team

In [54]:
import requests
import pandas as pd

def obtener_xg(id_liga, season_in=2025, season_out=2026, pais="ESP"):
    temporada = f"{season_in}/{season_out}"
    params = {"id": id_liga, "ccode3": pais, "season": temporada}

    # 1️⃣ Obtener JSON principal
    r = requests.get("https://www.fotmob.com/api/data/leagues", params=params)
    data = r.json()

    # 2️⃣ Buscar el bloque de expected_goals_team
    stats = data.get("stats", {})
    equipos_stats = stats.get("teams", [])

    fetch_url = None
    for bloque in equipos_stats:
        if bloque.get("name") == "expected_goals_team":
            fetch_url = bloque.get("fetchAllUrl")
            break

    if not fetch_url:
        print("⚠ No se encontró fetchAllUrl para expected_goals_team")
        return None

    # 3️⃣ Corregir la URL
    if fetch_url.startswith("//"):
        fetch_url = "https:" + fetch_url
    elif fetch_url.startswith("/"):
        fetch_url = "https://www.fotmob.com" + fetch_url

    # 4️⃣ Obtener los datos reales
    r2 = requests.get(fetch_url)
    datos_xg = r2.json()

    # 5️⃣ Extraer los valores desde TopLists[0]["StatList"]
    stat_list = datos_xg["TopLists"][0]["StatList"]

    filas = []
    for equipo in stat_list:
        fila = {
            "team": equipo.get("ParticipantName"),
            "played": equipo.get("MatchesPlayed"),
            "xG": equipo.get("StatValue"),
            "xGA": equipo.get("SubStatValue"),
        }
        filas.append(fila)

    df = pd.DataFrame(filas)
    df["Temporada"] = temporada

    columnas_finales = ["Temporada", "team", "played", "xG", "xGA"]
    df = df[columnas_finales]

    return df


# -----------------------------
# Ejemplo de uso
# -----------------------------
ligas = {
    "Premier League": 47,
    "LaLiga": 87,
    "Serie A": 55,
    "Bundesliga": 54,
    "Ligue 1": 53
}

season_in = 2025
season_out = 2026

for nombre_liga, id_liga in ligas.items():
    print(f"\n🏆 {nombre_liga}")
    df_xg = obtener_xg(id_liga, season_in, season_out)
    display(df_xg.head())

🏆 Premier League

   Temporada               team  played    xG   xGA
0  2025/2026    Manchester City      38  71.3  77.0
1  2025/2026            Chelsea      38  66.5  58.0
2  2025/2026            Arsenal      38  65.6  71.0
3  2025/2026  Manchester United      38  65.5  69.0
4  2025/2026    AFC Bournemouth      38  61.9  58.0

🏆 LaLiga

   Temporada             team  played    xG   xGA
0  2025/2026        Barcelona      38  86.7  95.0
1  2025/2026      Real Madrid      38  77.9  77.0
2  2025/2026       Villarreal      38  59.0  72.0
3  2025/2026  Atletico Madrid      38  58.9  62.0
4  2025/2026       Real Betis      38  55.6  59.0

🏆 Serie A

   Temporada      team  played    xG   xGA
0  2025/2026     Inter      38  72.2  89.0
1  2025/2026  Juventus      38  68.9  61.0
2  2025/2026      Como      38  61.9  65.0
3  2025/2026     Milan      38  60.3  53.0
4  2025/2026  Atalanta      38  57.9  51.0

🏆 Bundesliga

   Temporada               team  played     xG    xGA
0  2025/2026     Bayern München      34  100.7  122.0
1  2025/2026         RB Leipzig      34   67.4   66.0
2  2025/2026   Bayer Leverkusen      34   65.7   68.0
3  2025/2026  Borussia Dortmund      34   63.8   70.0
4  2025/2026      VfB Stuttgart      34   60.4   71.0

🏆 Ligue 1

   Temporada                 team  played    xG   xGA
0  2025/2026  Paris Saint-Germain      34  72.1  74.0
1  2025/2026                 Lens      34  67.7  66.0
2  2025/2026            Marseille      34  61.9  63.0
3  2025/2026               Monaco      34  57.9  60.0
4  2025/2026                Lille      34  55.3  52.0

In [57]:
import requests
import pandas as pd

BASE_URL = "https://www.fotmob.com/api/data/leagues"

ligas = {
    "Premier League": 47,
    "LaLiga": 87,
    "Serie A": 55,
    "Bundesliga": 54,
    "Ligue 1": 53
}

# -----------------------------
# FUNCIÓN xG (LA QUE YA FUNCIONA)
# -----------------------------
def obtener_xg(id_liga, season_in=2025, season_out=2026, pais="ESP"):
    temporada = f"{season_in}/{season_out}"
    params = {"id": id_liga, "ccode3": pais, "season": temporada}

    r = requests.get("https://www.fotmob.com/api/data/leagues", params=params)
    data = r.json()

    stats = data.get("stats", {})
    equipos_stats = stats.get("teams", [])

    fetch_url = None
    for bloque in equipos_stats:
        if bloque.get("name") == "expected_goals_team":
            fetch_url = bloque.get("fetchAllUrl")
            break

    if not fetch_url:
        print("⚠ No se encontró fetchAllUrl para expected_goals_team")
        return None

    if fetch_url.startswith("//"):
        fetch_url = "https:" + fetch_url
    elif fetch_url.startswith("/"):
        fetch_url = "https://www.fotmob.com" + fetch_url

    r2 = requests.get(fetch_url)
    datos_xg = r2.json()

    stat_list = datos_xg["TopLists"][0]["StatList"]

    filas = []
    for equipo in stat_list:
        fila = {
            "team": equipo.get("ParticipantName"),
            "played": equipo.get("MatchesPlayed"),
            "xG": equipo.get("StatValue"),
            "xGA": equipo.get("SubStatValue"),
        }
        filas.append(fila)

    df = pd.DataFrame(filas)
    df["Temporada"] = temporada

    columnas_finales = ["Temporada", "team", "played", "xG", "xGA"]
    df = df[columnas_finales]

    return df


# -----------------------------
# FUNCIÓN 1: Extraer ALL / HOME / AWAY / LAST5
# -----------------------------
def extraer_tablas(data):
    tablas = data.get("table", [])
    resultados = {"all": None, "home": None, "away": None, "last5": None}

    for bloque in tablas:
        tabla_obj = bloque.get("data", {}).get("table", {})
        if not isinstance(tabla_obj, dict):
            continue

        for tipo in ["all", "home", "away", "form"]:
            if tipo in tabla_obj:
                df = pd.DataFrame(tabla_obj[tipo])
                if "team" in df.columns:
                    df["logoUrl"] = df["team"].apply(lambda t: t.get("logo") if isinstance(t, dict) else None)
                    df["name"] = df["team"].apply(lambda t: t.get("name") if isinstance(t, dict) else None)
                    df["shortName"] = df["team"].apply(lambda t: t.get("shortName") if isinstance(t, dict) else None)
                resultados["last5" if tipo == "form" else tipo] = df

    return resultados


# -----------------------------
# FUNCIÓN 2: Preparar DataFrames
# -----------------------------
def preparar_tablas(tablas_dict, nombre_liga, temporada):
    preparados = {}
    for tipo, df in tablas_dict.items():
        if df is not None:
            df = df.copy()
            df["Liga"] = nombre_liga
            df["Tipo"] = tipo
            df["Temporada"] = temporada
            columnas = ["Liga", "Tipo", "Temporada"] + [c for c in df.columns if c not in ["Liga", "Tipo", "Temporada"]]
            df = df[columnas]
            preparados[tipo] = df
    return preparados


# -----------------------------
# FUNCIÓN 3: Obtener clasificación + xG
# -----------------------------
def obtener_clasificacion(id_liga, nombre_liga, season_in=2025, season_out=2026, pais="ESP"):
    temporada = f"{season_in}/{season_out}"
    params = {"id": id_liga, "ccode3": pais, "season": temporada}
    r = requests.get(BASE_URL, params=params)
    data = r.json()

    # tablas de clasificación
    tablas = extraer_tablas(data)
    tablas_preparadas = preparar_tablas(tablas, nombre_liga, temporada)

    # xG usando la función que ya funciona
    df_xg = obtener_xg(id_liga, season_in, season_out, pais)
    if df_xg is not None:
        df_xg = df_xg.copy()
        df_xg["Liga"] = nombre_liga
        df_xg["Tipo"] = "xG"
        columnas = ["Liga", "Tipo"] + [c for c in df_xg.columns if c not in ["Liga", "Tipo"]]
        df_xg = df_xg[columnas]
        tablas_preparadas["xG"] = df_xg

    return tablas_preparadas


# -----------------------------
# PROCESO PRINCIPAL
# -----------------------------
clasificaciones = {}

season_in = 2025
season_out = 2026

for nombre_liga, id_liga in ligas.items():
    print(f"\n🏆 {nombre_liga}")
    tablas = obtener_clasificacion(id_liga, nombre_liga, season_in, season_out)
    clasificaciones[nombre_liga] = tablas

    for tipo, df in tablas.items():
        print(f"\n📌 {nombre_liga} — {tipo.upper()}")
        if df is not None:
            display(df.head())
        else:
            print("No disponible")

🏆 Premier League

📌 Premier League — ALL

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,pts,idx,qualColor
0,Premier League,all,2025/2026,Arsenal,Arsenal,9825,/teams/9825/overview/arsenal,None,None,38,26,7,5,71-27,44,85,1,#2AD572
1,Premier League,all,2025/2026,Manchester City,Man City,8456,/teams/8456/overview/manchester-city,None,None,38,23,9,6,77-35,42,78,2,#2AD572
2,Premier League,all,2025/2026,Manchester United,Man United,10260,/teams/10260/overview/manchester-united,None,None,38,20,11,7,69-50,19,71,3,#2AD572
3,Premier League,all,2025/2026,Aston Villa,Aston Villa,10252,/teams/10252/overview/aston-villa,None,None,38,19,8,11,56-49,7,65,4,#2AD572
4,Premier League,all,2025/2026,Liverpool,Liverpool,8650,/teams/8650/overview/liverpool,None,None,38,17,9,12,63-53,10,60,5,#2AD572

📌 Premier League — HOME

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,idx,qualColor
0,Premier League,home,2025/2026,Arsenal,Arsenal,9825,/teams/9825/overview/arsenal,None,None,19,15,2,2,41-11,30,41,47,1,#2AD572
1,Premier League,home,2025/2026,Manchester City,Man City,8456,/teams/8456/overview/manchester-city,None,None,19,14,3,2,45-14,31,45,45,2,#2AD572
2,Premier League,home,2025/2026,Manchester United,Man United,10260,/teams/10260/overview/manchester-united,None,None,19,13,3,3,39-24,15,39,42,3,#2AD572
3,Premier League,home,2025/2026,Aston Villa,Aston Villa,10252,/teams/10252/overview/aston-villa,None,None,19,12,2,5,32-22,10,32,38,4,#2AD572
4,Premier League,home,2025/2026,Liverpool,Liverpool,8650,/teams/8650/overview/liverpool,None,None,19,10,6,3,34-20,14,34,36,5,#2AD572

📌 Premier League — AWAY

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,idx,qualColor
0,Premier League,away,2025/2026,Arsenal,Arsenal,9825,/teams/9825/overview/arsenal,None,None,19,11,5,3,30-16,14,30,38,1,#2AD572
1,Premier League,away,2025/2026,Manchester City,Man City,8456,/teams/8456/overview/manchester-city,None,None,19,9,6,4,32-21,11,32,33,2,#2AD572
2,Premier League,away,2025/2026,Manchester United,Man United,10260,/teams/10260/overview/manchester-united,None,None,19,7,8,4,30-26,4,30,29,3,#2AD572
3,Premier League,away,2025/2026,Aston Villa,Aston Villa,10252,/teams/10252/overview/aston-villa,None,None,19,7,6,6,24-27,-3,24,27,4,#2AD572
4,Premier League,away,2025/2026,Chelsea,Chelsea,8455,/teams/8455/overview/chelsea,None,None,19,7,5,7,32-27,5,32,26,5,#2AD572

📌 Premier League — LAST5

,Liga,Tipo,Temporada,name,shortName,featuredInMatch,id,pageUrl,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,ongoing,idx,qualColor
0,Premier League,last5,2025/2026,Arsenal,Arsenal,False,9825,/teams/9825/overview/arsenal,5,5,0,0,8-1,7,8,15,None,1,#2AD572
1,Premier League,last5,2025/2026,Manchester United,Man United,False,10260,/teams/10260/overview/manchester-united,5,4,1,0,11-5,6,11,13,None,2,#2AD572
2,Premier League,last5,2025/2026,Tottenham Hotspur,Tottenham,False,8586,/teams/8586/overview/tottenham-hotspur,5,3,1,1,6-4,2,6,10,None,3,#2AD572
3,Premier League,last5,2025/2026,AFC Bournemouth,Bournemouth,False,8678,/teams/8678/overview/afc-bournemouth,5,2,3,0,8-4,4,8,9,None,4,#2AD572
4,Premier League,last5,2025/2026,Nottingham Forest,Nottm Forest,False,10203,/teams/10203/overview/nottingham-forest,5,2,2,1,12-6,6,12,8,None,5,#2AD572

📌 Premier League — XG

             Liga Tipo  Temporada               team  played    xG   xGA
0  Premier League   xG  2025/2026    Manchester City      38  71.3  77.0
1  Premier League   xG  2025/2026            Chelsea      38  66.5  58.0
2  Premier League   xG  2025/2026            Arsenal      38  65.6  71.0
3  Premier League   xG  2025/2026  Manchester United      38  65.5  69.0
4  Premier League   xG  2025/2026    AFC Bournemouth      38  61.9  58.0

🏆 LaLiga

📌 LaLiga — ALL

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,pts,idx,qualColor
0,LaLiga,all,2025/2026,Barcelona,Barcelona,8634,/teams/8634/overview/barcelona,None,None,38,31,1,6,95-36,59,94,1,#2AD572
1,LaLiga,all,2025/2026,Real Madrid,Real Madrid,8633,/teams/8633/overview/real-madrid,None,None,38,27,5,6,77-35,42,86,2,#2AD572
2,LaLiga,all,2025/2026,Villarreal,Villarreal,10205,/teams/10205/overview/villarreal,None,None,38,22,6,10,72-46,26,72,3,#2AD572
3,LaLiga,all,2025/2026,Atletico Madrid,Atletico Madrid,9906,/teams/9906/overview/atletico-madrid,None,None,38,21,6,11,62-44,18,69,4,#2AD572
4,LaLiga,all,2025/2026,Real Betis,Real Betis,8603,/teams/8603/overview/real-betis,None,None,38,15,15,8,59-48,11,60,5,#2AD572

📌 LaLiga — HOME

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,idx,qualColor
0,LaLiga,home,2025/2026,Barcelona,Barcelona,8634,/teams/8634/overview/barcelona,None,None,19,19,0,0,57-10,47,57,57,1,#2AD572
1,LaLiga,home,2025/2026,Real Madrid,Real Madrid,8633,/teams/8633/overview/real-madrid,None,None,19,16,1,2,45-16,29,45,49,2,#2AD572
2,LaLiga,home,2025/2026,Villarreal,Villarreal,10205,/teams/10205/overview/villarreal,None,None,19,15,1,3,48-19,29,48,46,3,#2AD572
3,LaLiga,home,2025/2026,Atletico Madrid,Atletico Madrid,9906,/teams/9906/overview/atletico-madrid,None,None,19,15,1,3,39-17,22,39,46,4,#2AD572
4,LaLiga,home,2025/2026,Real Betis,Real Betis,8603,/teams/8603/overview/real-betis,None,None,19,10,6,3,34-19,15,34,36,5,#2AD572

📌 LaLiga — AWAY

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,idx,qualColor
0,LaLiga,away,2025/2026,Real Madrid,Real Madrid,8633,/teams/8633/overview/real-madrid,None,None,19,11,4,4,32-19,13,32,37,1,#2AD572
1,LaLiga,away,2025/2026,Barcelona,Barcelona,8634,/teams/8634/overview/barcelona,None,None,19,12,1,6,38-26,12,38,37,2,#2AD572
2,LaLiga,away,2025/2026,Celta Vigo,Celta Vigo,9910,/teams/9910/overview/celta-vigo,None,None,19,8,7,4,24-20,4,24,31,3,#2AD572
3,LaLiga,away,2025/2026,Villarreal,Villarreal,10205,/teams/10205/overview/villarreal,None,None,19,7,5,7,24-27,-3,24,26,4,#2AD572
4,LaLiga,away,2025/2026,Real Betis,Real Betis,8603,/teams/8603/overview/real-betis,None,None,19,5,9,5,25-29,-4,25,24,5,#2AD572

📌 LaLiga — LAST5

,Liga,Tipo,Temporada,name,shortName,featuredInMatch,id,pageUrl,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,ongoing,idx,qualColor
0,LaLiga,last5,2025/2026,Real Madrid,Real Madrid,False,8633,/teams/8633/overview/real-madrid,5,4,0,1,9-4,5,9,12,None,1,#2AD572
1,LaLiga,last5,2025/2026,Rayo Vallecano,Rayo Vallecano,False,8370,/teams/8370/overview/rayo-vallecano,5,3,2,0,8-3,5,8,11,None,2,#2AD572
2,LaLiga,last5,2025/2026,Real Betis,Real Betis,False,8603,/teams/8603/overview/real-betis,5,3,1,1,10-7,3,10,10,None,3,#2AD572
3,LaLiga,last5,2025/2026,Celta Vigo,Celta Vigo,False,9910,/teams/9910/overview/celta-vigo,5,3,1,1,8-5,3,8,10,None,4,#2AD572
4,LaLiga,last5,2025/2026,Valencia,Valencia,False,10267,/teams/10267/overview/valencia,5,3,1,1,9-7,2,9,10,None,5,#2AD572

📌 LaLiga — XG

     Liga Tipo  Temporada             team  played    xG   xGA
0  LaLiga   xG  2025/2026        Barcelona      38  86.7  95.0
1  LaLiga   xG  2025/2026      Real Madrid      38  77.9  77.0
2  LaLiga   xG  2025/2026       Villarreal      38  59.0  72.0
3  LaLiga   xG  2025/2026  Atletico Madrid      38  58.9  62.0
4  LaLiga   xG  2025/2026       Real Betis      38  55.6  59.0

🏆 Serie A

📌 Serie A — ALL

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,pts,idx,qualColor
0,Serie A,all,2025/2026,Inter,Inter,8636,/teams/8636/overview/inter,None,None,38,27,6,5,89-35,54,87,1,#2AD572
1,Serie A,all,2025/2026,Napoli,Napoli,9875,/teams/9875/overview/napoli,None,None,38,23,7,8,58-36,22,76,2,#2AD572
2,Serie A,all,2025/2026,Roma,Roma,8686,/teams/8686/overview/roma,None,None,38,23,4,11,59-31,28,73,3,#2AD572
3,Serie A,all,2025/2026,Como,Como,10171,/teams/10171/overview/como,None,None,38,20,11,7,65-29,36,71,4,#2AD572
4,Serie A,all,2025/2026,Milan,Milan,8564,/teams/8564/overview/milan,None,None,38,20,10,8,53-35,18,70,5,#0046A7

📌 Serie A — HOME

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,idx,qualColor
0,Serie A,home,2025/2026,Inter,Inter,8636,/teams/8636/overview/inter,None,None,19,14,3,2,50-16,34,50,45,1,#2AD572
1,Serie A,home,2025/2026,Napoli,Napoli,9875,/teams/9875/overview/napoli,None,None,19,13,4,2,33-18,15,33,43,2,#2AD572
2,Serie A,home,2025/2026,Roma,Roma,8686,/teams/8686/overview/roma,None,None,19,13,3,3,33-10,23,33,42,3,#2AD572
3,Serie A,home,2025/2026,Juventus,Juventus,9885,/teams/9885/overview/juventus,None,None,19,10,7,2,35-16,19,35,37,4,#2AD572
4,Serie A,home,2025/2026,Como,Como,10171,/teams/10171/overview/como,None,None,19,10,6,3,35-15,20,35,36,5,#0046A7

📌 Serie A — AWAY

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,idx,qualColor
0,Serie A,away,2025/2026,Inter,Inter,8636,/teams/8636/overview/inter,None,None,19,13,3,3,39-19,20,39,42,1,#2AD572
1,Serie A,away,2025/2026,Milan,Milan,8564,/teams/8564/overview/milan,None,None,19,11,5,3,28-14,14,28,38,2,#2AD572
2,Serie A,away,2025/2026,Como,Como,10171,/teams/10171/overview/como,None,None,19,10,5,4,30-14,16,30,35,3,#2AD572
3,Serie A,away,2025/2026,Bologna,Bologna,9857,/teams/9857/overview/bologna,None,None,19,10,4,5,30-23,7,30,34,4,#2AD572
4,Serie A,away,2025/2026,Napoli,Napoli,9875,/teams/9875/overview/napoli,None,None,19,10,3,6,25-18,7,25,33,5,#0046A7

📌 Serie A — LAST5

,Liga,Tipo,Temporada,name,shortName,featuredInMatch,id,pageUrl,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,ongoing,idx,qualColor
0,Serie A,last5,2025/2026,Roma,Roma,False,8686,/teams/8686/overview/roma,5,5,0,0,13-2,11,13,15,None,1,#2AD572
1,Serie A,last5,2025/2026,Como,Como,False,10171,/teams/10171/overview/como,5,4,1,0,8-1,7,8,13,None,2,#2AD572
2,Serie A,last5,2025/2026,Napoli,Napoli,False,9875,/teams/9875/overview/napoli,5,3,1,1,10-3,7,10,10,None,3,#2AD572
3,Serie A,last5,2025/2026,Lecce,Lecce,False,9888,/teams/9888/overview/lecce,5,3,1,1,6-4,2,6,10,None,4,#2AD572
4,Serie A,last5,2025/2026,Cagliari,Cagliari,False,8529,/teams/8529/overview/cagliari,5,3,1,1,7-6,1,7,10,None,5,#0046A7

📌 Serie A — XG

      Liga Tipo  Temporada      team  played    xG   xGA
0  Serie A   xG  2025/2026     Inter      38  72.2  89.0
1  Serie A   xG  2025/2026  Juventus      38  68.9  61.0
2  Serie A   xG  2025/2026      Como      38  61.9  65.0
3  Serie A   xG  2025/2026     Milan      38  60.3  53.0
4  Serie A   xG  2025/2026  Atalanta      38  57.9  51.0

🏆 Bundesliga

📌 Bundesliga — ALL

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,pts,idx,qualColor
0,Bundesliga,all,2025/2026,Bayern München,Bayern München,9823,/teams/9823/overview/bayern-munchen,None,None,34,28,5,1,122-36,86,89,1,#2AD572
1,Bundesliga,all,2025/2026,Borussia Dortmund,Dortmund,9789,/teams/9789/overview/borussia-dortmund,None,None,34,22,7,5,70-34,36,73,2,#2AD572
2,Bundesliga,all,2025/2026,RB Leipzig,RB Leipzig,178475,/teams/178475/overview/rb-leipzig,None,None,34,20,5,9,66-47,19,65,3,#2AD572
3,Bundesliga,all,2025/2026,VfB Stuttgart,VfB Stuttgart,10269,/teams/10269/overview/vfb-stuttgart,None,None,34,18,8,8,71-49,22,62,4,#2AD572
4,Bundesliga,all,2025/2026,Hoffenheim,Hoffenheim,8226,/teams/8226/overview/hoffenheim,None,None,34,18,7,9,65-52,13,61,5,#0046A7

📌 Bundesliga — HOME

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,idx,qualColor
0,Bundesliga,home,2025/2026,Bayern München,Bayern München,9823,/teams/9823/overview/bayern-munchen,None,None,17,14,2,1,68-19,49,68,44,1,#2AD572
1,Bundesliga,home,2025/2026,Borussia Dortmund,Dortmund,9789,/teams/9789/overview/borussia-dortmund,None,None,17,13,2,2,40-16,24,40,41,2,#2AD572
2,Bundesliga,home,2025/2026,VfB Stuttgart,VfB Stuttgart,10269,/teams/10269/overview/vfb-stuttgart,None,None,17,12,3,2,30-16,14,30,39,3,#2AD572
3,Bundesliga,home,2025/2026,RB Leipzig,RB Leipzig,178475,/teams/178475/overview/rb-leipzig,None,None,17,12,2,3,40-20,20,40,38,4,#2AD572
4,Bundesliga,home,2025/2026,Hoffenheim,Hoffenheim,8226,/teams/8226/overview/hoffenheim,None,None,17,10,2,5,35-21,14,35,32,5,#0046A7

📌 Bundesliga — AWAY

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,idx,qualColor
0,Bundesliga,away,2025/2026,Bayern München,Bayern München,9823,/teams/9823/overview/bayern-munchen,None,None,17,14,3,0,54-17,37,54,45,1,#2AD572
1,Bundesliga,away,2025/2026,Borussia Dortmund,Dortmund,9789,/teams/9789/overview/borussia-dortmund,None,None,17,9,5,3,30-18,12,30,32,2,#2AD572
2,Bundesliga,away,2025/2026,Hoffenheim,Hoffenheim,8226,/teams/8226/overview/hoffenheim,None,None,17,8,5,4,30-31,-1,30,29,3,#2AD572
3,Bundesliga,away,2025/2026,Bayer Leverkusen,Leverkusen,8178,/teams/8178/overview/bayer-leverkusen,None,None,17,8,4,5,30-28,2,30,28,4,#2AD572
4,Bundesliga,away,2025/2026,RB Leipzig,RB Leipzig,178475,/teams/178475/overview/rb-leipzig,None,None,17,8,3,6,26-27,-1,26,27,5,#0046A7

📌 Bundesliga — LAST5

,Liga,Tipo,Temporada,name,shortName,featuredInMatch,id,pageUrl,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,ongoing,idx,qualColor
0,Bundesliga,last5,2025/2026,Bayern München,Bayern München,False,9823,/teams/9823/overview/bayern-munchen,5,4,1,0,17-9,8,17,13,None,1,#2AD572
1,Bundesliga,last5,2025/2026,Augsburg,Augsburg,False,8406,/teams/8406/overview/augsburg,5,3,1,1,9-8,1,9,10,None,2,#2AD572
2,Bundesliga,last5,2025/2026,Hoffenheim,Hoffenheim,False,8226,/teams/8226/overview/hoffenheim,5,3,1,1,8-9,-1,8,10,None,3,#2AD572
3,Bundesliga,last5,2025/2026,Borussia Dortmund,Dortmund,False,9789,/teams/9789/overview/borussia-dortmund,5,3,0,2,10-5,5,10,9,None,4,#2AD572
4,Bundesliga,last5,2025/2026,RB Leipzig,RB Leipzig,False,178475,/teams/178475/overview/rb-leipzig,5,3,0,2,10-11,-1,10,9,None,5,#0046A7

📌 Bundesliga — XG

         Liga Tipo  Temporada               team  played     xG    xGA
0  Bundesliga   xG  2025/2026     Bayern München      34  100.7  122.0
1  Bundesliga   xG  2025/2026         RB Leipzig      34   67.4   66.0
2  Bundesliga   xG  2025/2026   Bayer Leverkusen      34   65.7   68.0
3  Bundesliga   xG  2025/2026  Borussia Dortmund      34   63.8   70.0
4  Bundesliga   xG  2025/2026      VfB Stuttgart      34   60.4   71.0

🏆 Ligue 1

📌 Ligue 1 — ALL

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,pts,idx,qualColor
0,Ligue 1,all,2025/2026,Paris Saint-Germain,PSG,9847,/teams/9847/overview/paris-saint-germain,None,None,34,24,4,6,74-29,45,76,1,#2AD572
1,Ligue 1,all,2025/2026,Lens,Lens,8588,/teams/8588/overview/lens,None,None,34,22,4,8,66-35,31,70,2,#2AD572
2,Ligue 1,all,2025/2026,Lille,Lille,8639,/teams/8639/overview/lille,None,None,34,18,7,9,52-37,15,61,3,#2AD572
3,Ligue 1,all,2025/2026,Lyon,Lyon,9748,/teams/9748/overview/lyon,None,None,34,18,6,10,53-40,13,60,4,#FFD908
4,Ligue 1,all,2025/2026,Marseille,Marseille,8592,/teams/8592/overview/marseille,None,None,34,18,5,11,63-45,18,59,5,#0046A7

📌 Ligue 1 — HOME

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,idx,qualColor
0,Ligue 1,home,2025/2026,Lens,Lens,8588,/teams/8588/overview/lens,None,None,17,14,0,3,35-13,22,35,42,1,#2AD572
1,Ligue 1,home,2025/2026,Paris Saint-Germain,PSG,9847,/teams/9847/overview/paris-saint-germain,None,None,17,13,2,2,41-12,29,41,41,2,#2AD572
2,Ligue 1,home,2025/2026,Marseille,Marseille,8592,/teams/8592/overview/marseille,None,None,17,11,4,2,41-20,21,41,37,3,#2AD572
3,Ligue 1,home,2025/2026,Lyon,Lyon,9748,/teams/9748/overview/lyon,None,None,17,12,1,4,30-18,12,30,37,4,#FFD908
4,Ligue 1,home,2025/2026,Rennes,Rennes,9851,/teams/9851/overview/rennes,None,None,17,10,4,3,30-17,13,30,34,5,#0046A7

📌 Ligue 1 — AWAY

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,idx,qualColor
0,Ligue 1,away,2025/2026,Paris Saint-Germain,PSG,9847,/teams/9847/overview/paris-saint-germain,None,None,17,11,2,4,33-17,16,33,35,1,#2AD572
1,Ligue 1,away,2025/2026,Lille,Lille,8639,/teams/8639/overview/lille,None,None,17,10,2,5,28-20,8,28,32,2,#2AD572
2,Ligue 1,away,2025/2026,Lens,Lens,8588,/teams/8588/overview/lens,None,None,17,8,4,5,31-22,9,31,28,3,#2AD572
3,Ligue 1,away,2025/2026,Rennes,Rennes,9851,/teams/9851/overview/rennes,None,None,17,7,4,6,29-33,-4,29,25,4,#FFD908
4,Ligue 1,away,2025/2026,Lyon,Lyon,9748,/teams/9748/overview/lyon,None,None,17,6,5,6,23-22,1,23,23,5,#0046A7

📌 Ligue 1 — LAST5

,Liga,Tipo,Temporada,name,shortName,featuredInMatch,id,pageUrl,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,ongoing,idx,qualColor
0,Ligue 1,last5,2025/2026,Paris Saint-Germain,PSG,False,9847,/teams/9847/overview/paris-saint-germain,5,3,1,1,9-4,5,9,10,None,1,#2AD572
1,Ligue 1,last5,2025/2026,Auxerre,Auxerre,False,8583,/teams/8583/overview/auxerre,5,3,1,1,11-7,4,11,10,None,2,#2AD572
2,Ligue 1,last5,2025/2026,Strasbourg,Strasbourg,False,9848,/teams/9848/overview/strasbourg,5,3,1,1,12-10,2,12,10,None,3,#2AD572
3,Ligue 1,last5,2025/2026,Paris FC,Paris FC,False,6379,/teams/6379/overview/paris-fc,5,3,0,2,10-5,5,10,9,None,4,#FFD908
4,Ligue 1,last5,2025/2026,Rennes,Rennes,False,9851,/teams/9851/overview/rennes,5,3,0,2,10-9,1,10,9,None,5,#0046A7

📌 Ligue 1 — XG

      Liga Tipo  Temporada                 team  played    xG   xGA
0  Ligue 1   xG  2025/2026  Paris Saint-Germain      34  72.1  74.0
1  Ligue 1   xG  2025/2026                 Lens      34  67.7  66.0
2  Ligue 1   xG  2025/2026            Marseille      34  61.9  63.0
3  Ligue 1   xG  2025/2026               Monaco      34  57.9  60.0
4  Ligue 1   xG  2025/2026                Lille      34  55.3  52.0

In [65]:
import requests
import pandas as pd

def obtener_metricas_completas(id_liga, season_in=2025, season_out=2026, pais="ENG"):
    temporada = f"{season_in}/{season_out}"
    params = {"id": id_liga, "ccode3": pais, "season": temporada}

    # 1️⃣ Obtener JSON principal
    r = requests.get("https://www.fotmob.com/api/data/leagues", params=params)
    data = r.json()

    stats = data.get("stats", {})
    equipos_stats = stats.get("teams", [])

    # 2️⃣ Buscar todos los endpoints relevantes
    fetch_urls = {}
    for bloque in equipos_stats:
        nombre = bloque.get("name")
        if nombre in [
            "expected_goals_team",
            "expected_points_team",
            "expected_goals_conceded_team",
            "_xg_diff_team",
            "_xpts_diff_team"
        ]:
            fetch_urls[nombre] = bloque.get("fetchAllUrl")

    resultados = {}

    # 3️⃣ Descargar cada endpoint y convertirlo en DataFrame
    for nombre, url in fetch_urls.items():
        if not url:
            continue
        if url.startswith("//"):
            url = "https:" + url
        elif url.startswith("/"):
            url = "https://www.fotmob.com" + url

        r2 = requests.get(url)
        datos = r2.json()

        if "TopLists" not in datos or not datos["TopLists"]:
            continue

        stat_list = datos["TopLists"][0].get("StatList", [])
        if not stat_list:
            continue

        df = pd.DataFrame(stat_list)
        df.rename(columns={
            "ParticipantName": "team",
            "MatchesPlayed": "played",
            "StatValue": nombre.replace("_team", ""),
            "SubStatValue": nombre.replace("_team", "") + "_sub",
            "Rank": "rank"
        }, inplace=True)

        resultados[nombre] = df[["team", "played", "rank",
                                 nombre.replace("_team", ""),
                                 nombre.replace("_team", "") + "_sub"]]

    # 4️⃣ Unir todas las métricas
    df_final = None
    for df in resultados.values():
        if df_final is None:
            df_final = df
        else:
            df_final = df_final.merge(df, on=["team", "played"], how="outer")

    # 5️⃣ Añadir temporada y ordenar por expected_points (xPTS)
    df_final["Temporada"] = temporada
    if "expected_points" in df_final.columns:
        df_final = df_final.sort_values(by="expected_points", ascending=False)
    elif "expected_goals" in df_final.columns:
        df_final = df_final.sort_values(by="expected_goals", ascending=False)
    elif "rank" in df_final.columns:
        df_final = df_final.sort_values(by="rank", ascending=True)

    df_final.reset_index(drop=True, inplace=True)

    # 6️⃣ Calcular diferencias (xGDiff, xPTSDiff)
    if "expected_goals" in df_final.columns and "expected_goals_sub" in df_final.columns:
        df_final["xGDiff"] = df_final["expected_goals"] - df_final["expected_goals_sub"]
    if "expected_points" in df_final.columns and "expected_points_sub" in df_final.columns:
        df_final["xPTSDiff"] = df_final["expected_points"] - df_final["expected_points_sub"]

    return df_final


# -----------------------------
# Ejemplo de uso
# -----------------------------
df = obtener_metricas_completas(47)  # Premier League
display(df)

,team,played,rank_x,expected_goals,expected_goals_sub,rank_y,_xg_diff,_xg_diff_sub,rank,expected_goals_conceded,expected_goals_conceded_sub,Temporada,xGDiff
0,Manchester City,38,1,71.3,77.0,2,27.1,42.0,2,44.2,35.0,2025/2026,-5.7
1,Chelsea,38,2,66.5,58.0,4,14.3,6.0,8,52.3,52.0,2025/2026,8.5
2,Arsenal,38,3,65.6,71.0,1,37.3,44.0,1,28.3,27.0,2025/2026,-5.4
3,Manchester United,38,4,65.5,69.0,3,16.9,19.0,4,48.6,50.0,2025/2026,-3.5
4,AFC Bournemouth,38,5,61.9,58.0,10,5.1,4.0,16,56.8,54.0,2025/2026,3.9
5,Liverpool,38,6,61.3,63.0,5,13.9,10.0,3,47.4,53.0,2025/2026,-1.7
6,Brentford,38,7,60.3,55.0,8,5.8,3.0,13,54.4,52.0,2025/2026,5.3
7,Crystal Palace,38,8,58.2,41.0,7,6.3,-10.0,7,51.9,51.0,2025/2026,17.2
8,Brighton & Hove Albion,38,9,57.9,52.0,6,8.8,6.0,5,49.1,46.0,2025/2026,5.9
9,Newcastle United,38,10,57.1,53.0,9,5.8,-2.0,6,51.3,55.0,2025/2026,4.1
10,Leeds United,38,11,54.2,49.0,11,-1.4,-7.0,14,55.7,56.0,2025/2026,5.2
11,Fulham,38,12,48.4,47.0,12,-4.9,-4.0,10,53.3,51.0,2025/2026,1.4
12,Aston Villa,38,13,48.2,56.0,13,-5.7,7.0,11,53.9,49.0,2025/2026,-7.8
13,Everton,38,14,46.7,47.0,14,-9.8,-3.0,15,56.5,50.0,2025/2026,-0.3
14,West Ham United,38,15,46.1,46.0,17,-13.5,-19.0,19,59.6,65.0,2025/2026,0.1
15,Nottingham Forest,38,16,46.0,48.0,15,-11.3,-3.0,17,57.3,51.0,2025/2026,-2.0
16,Tottenham Hotspur,38,17,40.0,48.0,16,-12.3,-9.0,9,52.3,57.0,2025/2026,-8.0
17,Sunderland,38,18,38.9,42.0,18,-15.6,-6.0,12,54.4,48.0,2025/2026,-3.1
18,Wolverhampton Wanderers,38,19,35.5,27.0,19,-24.0,-41.0,18,59.5,68.0,2025/2026,8.5
19,Burnley,38,20,32.5,38.0,20,-42.8,-37.0,20,75.4,75.0,2025/2026,-5.5

In [66]:
import requests
import pandas as pd

def obtener_metricas_completas(id_liga, season_in=2025, season_out=2026, pais="ENG"):
    temporada = f"{season_in}/{season_out}"
    params = {"id": id_liga, "ccode3": pais, "season": temporada}

    # 1️⃣ Obtener JSON principal
    r = requests.get("https://www.fotmob.com/api/data/leagues", params=params)
    data = r.json()

    stats = data.get("stats", {})
    equipos_stats = stats.get("teams", [])

    # 2️⃣ Buscar todos los endpoints relevantes
    fetch_urls = {}
    for bloque in equipos_stats:
        nombre = bloque.get("name")
        if nombre in [
            "expected_goals_team",
            "expected_points_team",
            "expected_goals_conceded_team",
            "_xg_diff_team",
            "_xpts_diff_team"
        ]:
            fetch_urls[nombre] = bloque.get("fetchAllUrl")

    resultados = {}

    # 3️⃣ Descargar cada endpoint y convertirlo en DataFrame
    for nombre, url in fetch_urls.items():
        if not url:
            continue
        if url.startswith("//"):
            url = "https:" + url
        elif url.startswith("/"):
            url = "https://www.fotmob.com" + url

        r2 = requests.get(url)
        datos = r2.json()

        if "TopLists" not in datos or not datos["TopLists"]:
            continue

        stat_list = datos["TopLists"][0].get("StatList", [])
        if not stat_list:
            continue

        df = pd.DataFrame(stat_list)
        df.rename(columns={
            "ParticipantName": "team",
            "MatchesPlayed": "played",
            "StatValue": nombre.replace("_team", ""),
            "SubStatValue": nombre.replace("_team", "") + "_sub",
            "Rank": "rank"
        }, inplace=True)

        resultados[nombre] = df[["team", "played", "rank",
                                 nombre.replace("_team", ""),
                                 nombre.replace("_team", "") + "_sub"]]

    # 4️⃣ Unir todas las métricas
    df_final = None
    for df in resultados.values():
        if df_final is None:
            df_final = df
        else:
            df_final = df_final.merge(df, on=["team", "played"], how="outer")

    # 5️⃣ Añadir temporada
    df_final["Temporada"] = temporada

    # 6️⃣ Calcular diferencias (xGDiff, xPTSDiff)
    if "expected_goals" in df_final.columns and "expected_goals_sub" in df_final.columns:
        df_final["xGDiff"] = df_final["expected_goals"] - df_final["expected_goals_sub"]
    if "expected_points" in df_final.columns and "expected_points_sub" in df_final.columns:
        df_final["xPTSDiff"] = df_final["expected_points"] - df_final["expected_points_sub"]

    # 7️⃣ Ordenar por rank y limpiar duplicados
    if "rank" in df_final.columns:
        df_final = df_final.sort_values(by="rank", ascending=True)

    # Eliminar columnas duplicadas de rank (rank_x, rank_y, etc.)
    cols_rank = [c for c in df_final.columns if c.startswith("rank_")]
    df_final = df_final.drop(columns=cols_rank, errors="ignore")

    df_final.reset_index(drop=True, inplace=True)

    return df_final


# -----------------------------
# Ejemplo de uso
# -----------------------------
df = obtener_metricas_completas(47)  # Premier League
display(df)

,team,played,expected_goals,expected_goals_sub,_xg_diff,_xg_diff_sub,rank,expected_goals_conceded,expected_goals_conceded_sub,Temporada,xGDiff
0,Arsenal,38,65.6,71.0,37.3,44.0,1,28.3,27.0,2025/2026,-5.4
1,Manchester City,38,71.3,77.0,27.1,42.0,2,44.2,35.0,2025/2026,-5.7
2,Liverpool,38,61.3,63.0,13.9,10.0,3,47.4,53.0,2025/2026,-1.7
3,Manchester United,38,65.5,69.0,16.9,19.0,4,48.6,50.0,2025/2026,-3.5
4,Brighton & Hove Albion,38,57.9,52.0,8.8,6.0,5,49.1,46.0,2025/2026,5.9
5,Newcastle United,38,57.1,53.0,5.8,-2.0,6,51.3,55.0,2025/2026,4.1
6,Crystal Palace,38,58.2,41.0,6.3,-10.0,7,51.9,51.0,2025/2026,17.2
7,Chelsea,38,66.5,58.0,14.3,6.0,8,52.3,52.0,2025/2026,8.5
8,Tottenham Hotspur,38,40.0,48.0,-12.3,-9.0,9,52.3,57.0,2025/2026,-8.0
9,Fulham,38,48.4,47.0,-4.9,-4.0,10,53.3,51.0,2025/2026,1.4
10,Aston Villa,38,48.2,56.0,-5.7,7.0,11,53.9,49.0,2025/2026,-7.8
11,Sunderland,38,38.9,42.0,-15.6,-6.0,12,54.4,48.0,2025/2026,-3.1
12,Brentford,38,60.3,55.0,5.8,3.0,13,54.4,52.0,2025/2026,5.3
13,Leeds United,38,54.2,49.0,-1.4,-7.0,14,55.7,56.0,2025/2026,5.2
14,Everton,38,46.7,47.0,-9.8,-3.0,15,56.5,50.0,2025/2026,-0.3
15,AFC Bournemouth,38,61.9,58.0,5.1,4.0,16,56.8,54.0,2025/2026,3.9
16,Nottingham Forest,38,46.0,48.0,-11.3,-3.0,17,57.3,51.0,2025/2026,-2.0
17,Wolverhampton Wanderers,38,35.5,27.0,-24.0,-41.0,18,59.5,68.0,2025/2026,8.5
18,West Ham United,38,46.1,46.0,-13.5,-19.0,19,59.6,65.0,2025/2026,0.1
19,Burnley,38,32.5,38.0,-42.8,-37.0,20,75.4,75.0,2025/2026,-5.5