In [1]:
!pip install requests
!pip install pandas

Requirement already satisfied: requests in .\mi_entorno\Lib\site-packages (2.34.2)
Requirement already satisfied: charset_normalizer<4,>=2 in .\mi_entorno\Lib\site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in .\mi_entorno\Lib\site-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in .\mi_entorno\Lib\site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in .\mi_entorno\Lib\site-packages (from requests) (2026.6.17)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in .\mi_entorno\Lib\site-packages (3.0.4)
Requirement already satisfied: numpy>=2.3.3 in .\mi_entorno\Lib\site-packages (from pandas) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in .\mi_entorno\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\mi_entorno\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\mi_entorno\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

5 grandes ligas

In [2]:
import requests
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

BASE_URL = "https://www.fotmob.com/api/data/leagues"

ligas = {
    "Premier League": {"id": 47, "pais": "ENG"},
    "LaLiga": {"id": 87, "pais": "ESP"},
    "Serie A": {"id": 55, "pais": "ITA"},
    "Bundesliga": {"id": 54, "pais": "GER"},
    "Ligue 1": {"id": 53, "pais": "FRA"},
}

# Nombres de columna de la tabla xG tal como los da fotmob -> nombres "bonitos"
RENOMBRE_XG = {
    "name": "team",
    "played": "J",
    "xg": "xG",
    "xgConceded": "xGA",
    "xPoints": "xPTS",
    "xgDiff": "xG_diff",
    "xgConcededDiff": "xGA_diff",
    "xPointsDiff": "xPTS_diff",
    "position": "pos_real",
    "xPosition": "pos_xG",
    "xPositionDiff": "pos_diff",
}

# dejamos teamId dentro para poder construir el logo; se puede quitar después si molesta
COLUMNAS_XG_UTILES = ["teamId", "team", "J", "xG", "xG_diff", "xGA", "xGA_diff", "xPTS", "xPTS_diff",
                      "pos_real", "pos_xG", "pos_diff"]


def _url_logo(team_id):
    if pd.isna(team_id):
        return None
    return f"https://images.fotmob.com/image_resources/logo/teamlogo/{int(team_id)}.png"


def anadir_logos(df):
    """Añade la columna 'logo' usando el id del equipo (id o teamId)."""
    df = df.copy()
    id_col = "id" if "id" in df.columns else ("teamId" if "teamId" in df.columns else None)
    if id_col is not None:
        df["logo"] = df[id_col].apply(_url_logo)
    return df


def extraer_tablas(data):
    """
    Todas las tablas (all/home/away/form/xg) viven en:
    data['table'][*]['data']['table'] = {"all":[...], "home":[...],
                                          "away":[...], "form":[...], "xg":[...]}
    """
    tablas = data.get("table", [])
    resultados = {"all": None, "home": None, "away": None, "last5": None, "xG": None}
    mapeo_tipos = {"all": "all", "home": "home", "away": "away", "form": "last5", "xg": "xG"}

    for bloque in tablas:
        tabla_obj = bloque.get("data", {}).get("table", {})
        if not isinstance(tabla_obj, dict):
            continue

        for clave_json, clave_salida in mapeo_tipos.items():
            if clave_json in tabla_obj and tabla_obj[clave_json]:
                df = pd.json_normalize(tabla_obj[clave_json], sep="_")

                # por si el equipo viniera anidado como dict en vez de columnas planas
                if "team" in df.columns and df["team"].apply(lambda t: isinstance(t, dict)).any():
                    df["logoUrl"] = df["team"].apply(lambda t: t.get("logo") if isinstance(t, dict) else None)
                    df["name"] = df["team"].apply(lambda t: t.get("name") if isinstance(t, dict) else None)
                    df["shortName"] = df["team"].apply(lambda t: t.get("shortName") if isinstance(t, dict) else None)

                # tabla xG -> renombrar a nombres tipo web y quedarnos con lo útil
                if clave_json == "xg":
                    df = df.rename(columns=RENOMBRE_XG)
                    df = df[[c for c in COLUMNAS_XG_UTILES if c in df.columns]]
                    df = df.sort_values("xPTS", ascending=False).reset_index(drop=True)

                df = anadir_logos(df)
                resultados[clave_salida] = df

    return resultados


def preparar_tablas(tablas_dict, nombre_liga, temporada):
    preparados = {}
    for tipo, df in tablas_dict.items():
        if df is not None:
            df = df.copy()
            df["Liga"] = nombre_liga
            df["Tipo"] = tipo
            df["Temporada"] = temporada
            columnas = ["Liga", "Tipo", "Temporada"] + [c for c in df.columns if c not in ["Liga", "Tipo", "Temporada"]]
            df = df[columnas]
            preparados[tipo] = df
    return preparados


def obtener_clasificacion(id_liga, nombre_liga, season_in=2025, season_out=2026, pais="ESP", debug=False):
    temporada = f"{season_in}/{season_out}"
    params = {"id": id_liga, "ccode3": pais, "season": temporada}
    r = requests.get(BASE_URL, params=params)
    r.raise_for_status()
    data = r.json()

    tablas = extraer_tablas(data)

    if debug:
        for tipo, df in tablas.items():
            print(f"  -> {tipo}: {'OK, columnas=' + str(list(df.columns)) if df is not None else 'NO ENCONTRADA'}")

    return preparar_tablas(tablas, nombre_liga, temporada)

In [3]:
clasificaciones = {}
season_in = 2025
season_out = 2026

for nombre_liga, info in ligas.items():
    print(f"\n🏆 {nombre_liga}")
    tablas = obtener_clasificacion(info["id"], nombre_liga, season_in, season_out, pais=info["pais"], debug=True)
    clasificaciones[nombre_liga] = tablas

    for tipo, df in tablas.items():
        print(f"\n📌 {nombre_liga} — {tipo.upper()}")
        if df is not None:
            display(df.head())
        else:
            print("No disponible")

🏆 Premier League
  -> all: OK, columnas=['name', 'shortName', 'id', 'pageUrl', 'deduction', 'ongoing', 'played', 'wins', 'draws', 'losses', 'scoresStr', 'goalConDiff', 'pts', 'idx', 'qualColor', 'logo']
  -> home: OK, columnas=['name', 'shortName', 'id', 'pageUrl', 'deduction', 'ongoing', 'played', 'wins', 'draws', 'losses', 'scoresStr', 'goalConDiff', 'goalsScored', 'pts', 'idx', 'qualColor', 'logo']
  -> away: OK, columnas=['name', 'shortName', 'id', 'pageUrl', 'deduction', 'ongoing', 'played', 'wins', 'draws', 'losses', 'scoresStr', 'goalConDiff', 'goalsScored', 'pts', 'idx', 'qualColor', 'logo']
  -> last5: OK, columnas=['name', 'shortName', 'featuredInMatch', 'id', 'pageUrl', 'played', 'wins', 'draws', 'losses', 'scoresStr', 'goalConDiff', 'goalsScored', 'pts', 'ongoing', 'idx', 'qualColor', 'logo']
  -> xG: OK, columnas=['teamId', 'team', 'J', 'xG', 'xG_diff', 'xGA', 'xGA_diff', 'xPTS', 'xPTS_diff', 'pos_real', 'pos_xG', 'pos_diff', 'logo']

📌 Premier League — ALL

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,pts,idx,qualColor,logo
0,Premier League,all,2025/2026,Arsenal,Arsenal,9825,/teams/9825/overview/arsenal,None,None,38,26,7,5,71-27,44,85,1,#2AD572,https://images.fotmob.com/image_resources/logo...
1,Premier League,all,2025/2026,Manchester City,Man City,8456,/teams/8456/overview/manchester-city,None,None,38,23,9,6,77-35,42,78,2,#2AD572,https://images.fotmob.com/image_resources/logo...
2,Premier League,all,2025/2026,Manchester United,Man United,10260,/teams/10260/overview/manchester-united,None,None,38,20,11,7,69-50,19,71,3,#2AD572,https://images.fotmob.com/image_resources/logo...
3,Premier League,all,2025/2026,Aston Villa,Aston Villa,10252,/teams/10252/overview/aston-villa,None,None,38,19,8,11,56-49,7,65,4,#2AD572,https://images.fotmob.com/image_resources/logo...
4,Premier League,all,2025/2026,Liverpool,Liverpool,8650,/teams/8650/overview/liverpool,None,None,38,17,9,12,63-53,10,60,5,#2AD572,https://images.fotmob.com/image_resources/logo...

📌 Premier League — HOME

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,idx,qualColor,logo
0,Premier League,home,2025/2026,Arsenal,Arsenal,9825,/teams/9825/overview/arsenal,None,None,19,15,2,2,41-11,30,41,47,1,#2AD572,https://images.fotmob.com/image_resources/logo...
1,Premier League,home,2025/2026,Manchester City,Man City,8456,/teams/8456/overview/manchester-city,None,None,19,14,3,2,45-14,31,45,45,2,#2AD572,https://images.fotmob.com/image_resources/logo...
2,Premier League,home,2025/2026,Manchester United,Man United,10260,/teams/10260/overview/manchester-united,None,None,19,13,3,3,39-24,15,39,42,3,#2AD572,https://images.fotmob.com/image_resources/logo...
3,Premier League,home,2025/2026,Aston Villa,Aston Villa,10252,/teams/10252/overview/aston-villa,None,None,19,12,2,5,32-22,10,32,38,4,#2AD572,https://images.fotmob.com/image_resources/logo...
4,Premier League,home,2025/2026,Liverpool,Liverpool,8650,/teams/8650/overview/liverpool,None,None,19,10,6,3,34-20,14,34,36,5,#2AD572,https://images.fotmob.com/image_resources/logo...

📌 Premier League — AWAY

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,idx,qualColor,logo
0,Premier League,away,2025/2026,Arsenal,Arsenal,9825,/teams/9825/overview/arsenal,None,None,19,11,5,3,30-16,14,30,38,1,#2AD572,https://images.fotmob.com/image_resources/logo...
1,Premier League,away,2025/2026,Manchester City,Man City,8456,/teams/8456/overview/manchester-city,None,None,19,9,6,4,32-21,11,32,33,2,#2AD572,https://images.fotmob.com/image_resources/logo...
2,Premier League,away,2025/2026,Manchester United,Man United,10260,/teams/10260/overview/manchester-united,None,None,19,7,8,4,30-26,4,30,29,3,#2AD572,https://images.fotmob.com/image_resources/logo...
3,Premier League,away,2025/2026,Aston Villa,Aston Villa,10252,/teams/10252/overview/aston-villa,None,None,19,7,6,6,24-27,-3,24,27,4,#2AD572,https://images.fotmob.com/image_resources/logo...
4,Premier League,away,2025/2026,Chelsea,Chelsea,8455,/teams/8455/overview/chelsea,None,None,19,7,5,7,32-27,5,32,26,5,#2AD572,https://images.fotmob.com/image_resources/logo...

📌 Premier League — LAST5

,Liga,Tipo,Temporada,name,shortName,featuredInMatch,id,pageUrl,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,ongoing,idx,qualColor,logo
0,Premier League,last5,2025/2026,Arsenal,Arsenal,False,9825,/teams/9825/overview/arsenal,5,5,0,0,8-1,7,8,15,None,1,#2AD572,https://images.fotmob.com/image_resources/logo...
1,Premier League,last5,2025/2026,Manchester United,Man United,False,10260,/teams/10260/overview/manchester-united,5,4,1,0,11-5,6,11,13,None,2,#2AD572,https://images.fotmob.com/image_resources/logo...
2,Premier League,last5,2025/2026,Tottenham Hotspur,Tottenham,False,8586,/teams/8586/overview/tottenham-hotspur,5,3,1,1,6-4,2,6,10,None,3,#2AD572,https://images.fotmob.com/image_resources/logo...
3,Premier League,last5,2025/2026,AFC Bournemouth,Bournemouth,False,8678,/teams/8678/overview/afc-bournemouth,5,2,3,0,8-4,4,8,9,None,4,#2AD572,https://images.fotmob.com/image_resources/logo...
4,Premier League,last5,2025/2026,Nottingham Forest,Nottm Forest,False,10203,/teams/10203/overview/nottingham-forest,5,2,2,1,12-6,6,12,8,None,5,#2AD572,https://images.fotmob.com/image_resources/logo...

📌 Premier League — XG

,Liga,Tipo,Temporada,teamId,team,J,xG,xG_diff,xGA,xGA_diff,xPTS,xPTS_diff,pos_real,pos_xG,pos_diff,logo
0,Premier League,xG,2025/2026,9825,Arsenal,38,65.5997,5.4003,28.3025,-1.3025,77.824531,7.175469,1,1,0,https://images.fotmob.com/image_resources/logo...
1,Premier League,xG,2025/2026,8456,Manchester City,38,71.3303,5.6697,44.1955,-9.1955,71.038303,6.961697,2,2,0,https://images.fotmob.com/image_resources/logo...
2,Premier League,xG,2025/2026,10260,Manchester United,38,65.4876,3.5124,48.5707,1.4293,62.288436,8.711564,3,3,0,https://images.fotmob.com/image_resources/logo...
3,Premier League,xG,2025/2026,8650,Liverpool,38,61.3487,1.6513,47.4282,5.5718,61.609077,-1.609077,4,4,1,https://images.fotmob.com/image_resources/logo...
4,Premier League,xG,2025/2026,8455,Chelsea,38,66.5331,-8.5331,52.2635,-0.2635,60.007062,-8.007062,5,5,5,https://images.fotmob.com/image_resources/logo...

🏆 LaLiga
  -> all: OK, columnas=['name', 'shortName', 'id', 'pageUrl', 'deduction', 'ongoing', 'played', 'wins', 'draws', 'losses', 'scoresStr', 'goalConDiff', 'pts', 'idx', 'qualColor', 'logo']
  -> home: OK, columnas=['name', 'shortName', 'id', 'pageUrl', 'deduction', 'ongoing', 'played', 'wins', 'draws', 'losses', 'scoresStr', 'goalConDiff', 'goalsScored', 'pts', 'idx', 'qualColor', 'logo']
  -> away: OK, columnas=['name', 'shortName', 'id', 'pageUrl', 'deduction', 'ongoing', 'played', 'wins', 'draws', 'losses', 'scoresStr', 'goalConDiff', 'goalsScored', 'pts', 'idx', 'qualColor', 'logo']
  -> last5: OK, columnas=['name', 'shortName', 'featuredInMatch', 'id', 'pageUrl', 'played', 'wins', 'draws', 'losses', 'scoresStr', 'goalConDiff', 'goalsScored', 'pts', 'ongoing', 'idx', 'qualColor', 'logo']
  -> xG: OK, columnas=['teamId', 'team', 'J', 'xG', 'xG_diff', 'xGA', 'xGA_diff', 'xPTS', 'xPTS_diff', 'pos_real', 'pos_xG', 'pos_diff', 'logo']

📌 LaLiga — ALL

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,pts,idx,qualColor,logo
0,LaLiga,all,2025/2026,Barcelona,Barcelona,8634,/teams/8634/overview/barcelona,None,None,38,31,1,6,95-36,59,94,1,#2AD572,https://images.fotmob.com/image_resources/logo...
1,LaLiga,all,2025/2026,Real Madrid,Real Madrid,8633,/teams/8633/overview/real-madrid,None,None,38,27,5,6,77-35,42,86,2,#2AD572,https://images.fotmob.com/image_resources/logo...
2,LaLiga,all,2025/2026,Villarreal,Villarreal,10205,/teams/10205/overview/villarreal,None,None,38,22,6,10,72-46,26,72,3,#2AD572,https://images.fotmob.com/image_resources/logo...
3,LaLiga,all,2025/2026,Atletico Madrid,Atletico Madrid,9906,/teams/9906/overview/atletico-madrid,None,None,38,21,6,11,62-44,18,69,4,#2AD572,https://images.fotmob.com/image_resources/logo...
4,LaLiga,all,2025/2026,Real Betis,Real Betis,8603,/teams/8603/overview/real-betis,None,None,38,15,15,8,59-48,11,60,5,#2AD572,https://images.fotmob.com/image_resources/logo...

📌 LaLiga — HOME

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,idx,qualColor,logo
0,LaLiga,home,2025/2026,Barcelona,Barcelona,8634,/teams/8634/overview/barcelona,None,None,19,19,0,0,57-10,47,57,57,1,#2AD572,https://images.fotmob.com/image_resources/logo...
1,LaLiga,home,2025/2026,Real Madrid,Real Madrid,8633,/teams/8633/overview/real-madrid,None,None,19,16,1,2,45-16,29,45,49,2,#2AD572,https://images.fotmob.com/image_resources/logo...
2,LaLiga,home,2025/2026,Villarreal,Villarreal,10205,/teams/10205/overview/villarreal,None,None,19,15,1,3,48-19,29,48,46,3,#2AD572,https://images.fotmob.com/image_resources/logo...
3,LaLiga,home,2025/2026,Atletico Madrid,Atletico Madrid,9906,/teams/9906/overview/atletico-madrid,None,None,19,15,1,3,39-17,22,39,46,4,#2AD572,https://images.fotmob.com/image_resources/logo...
4,LaLiga,home,2025/2026,Real Betis,Real Betis,8603,/teams/8603/overview/real-betis,None,None,19,10,6,3,34-19,15,34,36,5,#2AD572,https://images.fotmob.com/image_resources/logo...

📌 LaLiga — AWAY

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,idx,qualColor,logo
0,LaLiga,away,2025/2026,Real Madrid,Real Madrid,8633,/teams/8633/overview/real-madrid,None,None,19,11,4,4,32-19,13,32,37,1,#2AD572,https://images.fotmob.com/image_resources/logo...
1,LaLiga,away,2025/2026,Barcelona,Barcelona,8634,/teams/8634/overview/barcelona,None,None,19,12,1,6,38-26,12,38,37,2,#2AD572,https://images.fotmob.com/image_resources/logo...
2,LaLiga,away,2025/2026,Celta Vigo,Celta Vigo,9910,/teams/9910/overview/celta-vigo,None,None,19,8,7,4,24-20,4,24,31,3,#2AD572,https://images.fotmob.com/image_resources/logo...
3,LaLiga,away,2025/2026,Villarreal,Villarreal,10205,/teams/10205/overview/villarreal,None,None,19,7,5,7,24-27,-3,24,26,4,#2AD572,https://images.fotmob.com/image_resources/logo...
4,LaLiga,away,2025/2026,Real Betis,Real Betis,8603,/teams/8603/overview/real-betis,None,None,19,5,9,5,25-29,-4,25,24,5,#2AD572,https://images.fotmob.com/image_resources/logo...

📌 LaLiga — LAST5

,Liga,Tipo,Temporada,name,shortName,featuredInMatch,id,pageUrl,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,ongoing,idx,qualColor,logo
0,LaLiga,last5,2025/2026,Real Madrid,Real Madrid,False,8633,/teams/8633/overview/real-madrid,5,4,0,1,9-4,5,9,12,None,1,#2AD572,https://images.fotmob.com/image_resources/logo...
1,LaLiga,last5,2025/2026,Rayo Vallecano,Rayo Vallecano,False,8370,/teams/8370/overview/rayo-vallecano,5,3,2,0,8-3,5,8,11,None,2,#2AD572,https://images.fotmob.com/image_resources/logo...
2,LaLiga,last5,2025/2026,Real Betis,Real Betis,False,8603,/teams/8603/overview/real-betis,5,3,1,1,10-7,3,10,10,None,3,#2AD572,https://images.fotmob.com/image_resources/logo...
3,LaLiga,last5,2025/2026,Celta Vigo,Celta Vigo,False,9910,/teams/9910/overview/celta-vigo,5,3,1,1,8-5,3,8,10,None,4,#2AD572,https://images.fotmob.com/image_resources/logo...
4,LaLiga,last5,2025/2026,Valencia,Valencia,False,10267,/teams/10267/overview/valencia,5,3,1,1,9-7,2,9,10,None,5,#2AD572,https://images.fotmob.com/image_resources/logo...

📌 LaLiga — XG

,Liga,Tipo,Temporada,teamId,team,J,xG,xG_diff,xGA,xGA_diff,xPTS,xPTS_diff,pos_real,pos_xG,pos_diff,logo
0,LaLiga,xG,2025/2026,8633,Real Madrid,38,77.9322,-0.9322,41.1713,-6.1713,76.717886,9.282114,1,1,1,https://images.fotmob.com/image_resources/logo...
1,LaLiga,xG,2025/2026,8634,Barcelona,38,86.6960,8.3040,45.2865,-9.2865,76.390543,17.609457,2,2,-1,https://images.fotmob.com/image_resources/logo...
2,LaLiga,xG,2025/2026,10205,Villarreal,38,58.9703,13.0297,46.1904,-0.1904,61.201450,10.798550,3,3,0,https://images.fotmob.com/image_resources/logo...
3,LaLiga,xG,2025/2026,9906,Atletico Madrid,38,58.8685,3.1315,49.0217,-5.0217,58.935421,10.064579,4,4,0,https://images.fotmob.com/image_resources/logo...
4,LaLiga,xG,2025/2026,8603,Real Betis,38,55.6117,3.3883,46.6126,1.3874,58.828269,1.171731,5,5,0,https://images.fotmob.com/image_resources/logo...

🏆 Serie A
  -> all: OK, columnas=['name', 'shortName', 'id', 'pageUrl', 'deduction', 'ongoing', 'played', 'wins', 'draws', 'losses', 'scoresStr', 'goalConDiff', 'pts', 'idx', 'qualColor', 'logo']
  -> home: OK, columnas=['name', 'shortName', 'id', 'pageUrl', 'deduction', 'ongoing', 'played', 'wins', 'draws', 'losses', 'scoresStr', 'goalConDiff', 'goalsScored', 'pts', 'idx', 'qualColor', 'logo']
  -> away: OK, columnas=['name', 'shortName', 'id', 'pageUrl', 'deduction', 'ongoing', 'played', 'wins', 'draws', 'losses', 'scoresStr', 'goalConDiff', 'goalsScored', 'pts', 'idx', 'qualColor', 'logo']
  -> last5: OK, columnas=['name', 'shortName', 'featuredInMatch', 'id', 'pageUrl', 'played', 'wins', 'draws', 'losses', 'scoresStr', 'goalConDiff', 'goalsScored', 'pts', 'ongoing', 'idx', 'qualColor', 'logo']
  -> xG: OK, columnas=['teamId', 'team', 'J', 'xG', 'xG_diff', 'xGA', 'xGA_diff', 'xPTS', 'xPTS_diff', 'pos_real', 'pos_xG', 'pos_diff', 'logo']

📌 Serie A — ALL

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,pts,idx,qualColor,logo
0,Serie A,all,2025/2026,Inter,Inter,8636,/teams/8636/overview/inter,None,None,38,27,6,5,89-35,54,87,1,#2AD572,https://images.fotmob.com/image_resources/logo...
1,Serie A,all,2025/2026,Napoli,Napoli,9875,/teams/9875/overview/napoli,None,None,38,23,7,8,58-36,22,76,2,#2AD572,https://images.fotmob.com/image_resources/logo...
2,Serie A,all,2025/2026,Roma,Roma,8686,/teams/8686/overview/roma,None,None,38,23,4,11,59-31,28,73,3,#2AD572,https://images.fotmob.com/image_resources/logo...
3,Serie A,all,2025/2026,Como,Como,10171,/teams/10171/overview/como,None,None,38,20,11,7,65-29,36,71,4,#2AD572,https://images.fotmob.com/image_resources/logo...
4,Serie A,all,2025/2026,Milan,Milan,8564,/teams/8564/overview/milan,None,None,38,20,10,8,53-35,18,70,5,#0046A7,https://images.fotmob.com/image_resources/logo...

📌 Serie A — HOME

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,idx,qualColor,logo
0,Serie A,home,2025/2026,Inter,Inter,8636,/teams/8636/overview/inter,None,None,19,14,3,2,50-16,34,50,45,1,#2AD572,https://images.fotmob.com/image_resources/logo...
1,Serie A,home,2025/2026,Napoli,Napoli,9875,/teams/9875/overview/napoli,None,None,19,13,4,2,33-18,15,33,43,2,#2AD572,https://images.fotmob.com/image_resources/logo...
2,Serie A,home,2025/2026,Roma,Roma,8686,/teams/8686/overview/roma,None,None,19,13,3,3,33-10,23,33,42,3,#2AD572,https://images.fotmob.com/image_resources/logo...
3,Serie A,home,2025/2026,Juventus,Juventus,9885,/teams/9885/overview/juventus,None,None,19,10,7,2,35-16,19,35,37,4,#2AD572,https://images.fotmob.com/image_resources/logo...
4,Serie A,home,2025/2026,Como,Como,10171,/teams/10171/overview/como,None,None,19,10,6,3,35-15,20,35,36,5,#0046A7,https://images.fotmob.com/image_resources/logo...

📌 Serie A — AWAY

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,idx,qualColor,logo
0,Serie A,away,2025/2026,Inter,Inter,8636,/teams/8636/overview/inter,None,None,19,13,3,3,39-19,20,39,42,1,#2AD572,https://images.fotmob.com/image_resources/logo...
1,Serie A,away,2025/2026,Milan,Milan,8564,/teams/8564/overview/milan,None,None,19,11,5,3,28-14,14,28,38,2,#2AD572,https://images.fotmob.com/image_resources/logo...
2,Serie A,away,2025/2026,Como,Como,10171,/teams/10171/overview/como,None,None,19,10,5,4,30-14,16,30,35,3,#2AD572,https://images.fotmob.com/image_resources/logo...
3,Serie A,away,2025/2026,Bologna,Bologna,9857,/teams/9857/overview/bologna,None,None,19,10,4,5,30-23,7,30,34,4,#2AD572,https://images.fotmob.com/image_resources/logo...
4,Serie A,away,2025/2026,Napoli,Napoli,9875,/teams/9875/overview/napoli,None,None,19,10,3,6,25-18,7,25,33,5,#0046A7,https://images.fotmob.com/image_resources/logo...

📌 Serie A — LAST5

,Liga,Tipo,Temporada,name,shortName,featuredInMatch,id,pageUrl,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,ongoing,idx,qualColor,logo
0,Serie A,last5,2025/2026,Roma,Roma,False,8686,/teams/8686/overview/roma,5,5,0,0,13-2,11,13,15,None,1,#2AD572,https://images.fotmob.com/image_resources/logo...
1,Serie A,last5,2025/2026,Como,Como,False,10171,/teams/10171/overview/como,5,4,1,0,8-1,7,8,13,None,2,#2AD572,https://images.fotmob.com/image_resources/logo...
2,Serie A,last5,2025/2026,Napoli,Napoli,False,9875,/teams/9875/overview/napoli,5,3,1,1,10-3,7,10,10,None,3,#2AD572,https://images.fotmob.com/image_resources/logo...
3,Serie A,last5,2025/2026,Lecce,Lecce,False,9888,/teams/9888/overview/lecce,5,3,1,1,6-4,2,6,10,None,4,#2AD572,https://images.fotmob.com/image_resources/logo...
4,Serie A,last5,2025/2026,Cagliari,Cagliari,False,8529,/teams/8529/overview/cagliari,5,3,1,1,7-6,1,7,10,None,5,#0046A7,https://images.fotmob.com/image_resources/logo...

📌 Serie A — XG

,Liga,Tipo,Temporada,teamId,team,J,xG,xG_diff,xGA,xGA_diff,xPTS,xPTS_diff,pos_real,pos_xG,pos_diff,logo
0,Serie A,xG,2025/2026,8636,Inter,38,72.2110,16.7890,34.5840,0.4160,77.143834,9.856166,1,1,0,https://images.fotmob.com/image_resources/logo...
1,Serie A,xG,2025/2026,9885,Juventus,38,68.8922,-7.8922,32.9766,1.0234,75.245456,-6.245456,2,2,4,https://images.fotmob.com/image_resources/logo...
2,Serie A,xG,2025/2026,10171,Como,38,61.8922,3.1078,33.8610,-4.8610,69.166526,1.833474,3,3,1,https://images.fotmob.com/image_resources/logo...
3,Serie A,xG,2025/2026,8686,Roma,38,55.0395,3.9605,39.3462,-8.3462,63.776496,9.223504,4,4,-1,https://images.fotmob.com/image_resources/logo...
4,Serie A,xG,2025/2026,8524,Atalanta,38,57.8790,-6.8790,42.9872,-6.9872,63.637014,-4.637014,5,5,2,https://images.fotmob.com/image_resources/logo...

🏆 Bundesliga
  -> all: OK, columnas=['name', 'shortName', 'id', 'pageUrl', 'deduction', 'ongoing', 'played', 'wins', 'draws', 'losses', 'scoresStr', 'goalConDiff', 'pts', 'idx', 'qualColor', 'logo']
  -> home: OK, columnas=['name', 'shortName', 'id', 'pageUrl', 'deduction', 'ongoing', 'played', 'wins', 'draws', 'losses', 'scoresStr', 'goalConDiff', 'goalsScored', 'pts', 'idx', 'qualColor', 'logo']
  -> away: OK, columnas=['name', 'shortName', 'id', 'pageUrl', 'deduction', 'ongoing', 'played', 'wins', 'draws', 'losses', 'scoresStr', 'goalConDiff', 'goalsScored', 'pts', 'idx', 'qualColor', 'logo']
  -> last5: OK, columnas=['name', 'shortName', 'featuredInMatch', 'id', 'pageUrl', 'played', 'wins', 'draws', 'losses', 'scoresStr', 'goalConDiff', 'goalsScored', 'pts', 'ongoing', 'idx', 'qualColor', 'logo']
  -> xG: OK, columnas=['teamId', 'team', 'J', 'xG', 'xG_diff', 'xGA', 'xGA_diff', 'xPTS', 'xPTS_diff', 'pos_real', 'pos_xG', 'pos_diff', 'logo']

📌 Bundesliga — ALL

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,pts,idx,qualColor,logo
0,Bundesliga,all,2025/2026,Bayern München,Bayern München,9823,/teams/9823/overview/bayern-munchen,None,None,34,28,5,1,122-36,86,89,1,#2AD572,https://images.fotmob.com/image_resources/logo...
1,Bundesliga,all,2025/2026,Borussia Dortmund,Dortmund,9789,/teams/9789/overview/borussia-dortmund,None,None,34,22,7,5,70-34,36,73,2,#2AD572,https://images.fotmob.com/image_resources/logo...
2,Bundesliga,all,2025/2026,RB Leipzig,RB Leipzig,178475,/teams/178475/overview/rb-leipzig,None,None,34,20,5,9,66-47,19,65,3,#2AD572,https://images.fotmob.com/image_resources/logo...
3,Bundesliga,all,2025/2026,VfB Stuttgart,VfB Stuttgart,10269,/teams/10269/overview/vfb-stuttgart,None,None,34,18,8,8,71-49,22,62,4,#2AD572,https://images.fotmob.com/image_resources/logo...
4,Bundesliga,all,2025/2026,Hoffenheim,Hoffenheim,8226,/teams/8226/overview/hoffenheim,None,None,34,18,7,9,65-52,13,61,5,#0046A7,https://images.fotmob.com/image_resources/logo...

📌 Bundesliga — HOME

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,idx,qualColor,logo
0,Bundesliga,home,2025/2026,Bayern München,Bayern München,9823,/teams/9823/overview/bayern-munchen,None,None,17,14,2,1,68-19,49,68,44,1,#2AD572,https://images.fotmob.com/image_resources/logo...
1,Bundesliga,home,2025/2026,Borussia Dortmund,Dortmund,9789,/teams/9789/overview/borussia-dortmund,None,None,17,13,2,2,40-16,24,40,41,2,#2AD572,https://images.fotmob.com/image_resources/logo...
2,Bundesliga,home,2025/2026,VfB Stuttgart,VfB Stuttgart,10269,/teams/10269/overview/vfb-stuttgart,None,None,17,12,3,2,30-16,14,30,39,3,#2AD572,https://images.fotmob.com/image_resources/logo...
3,Bundesliga,home,2025/2026,RB Leipzig,RB Leipzig,178475,/teams/178475/overview/rb-leipzig,None,None,17,12,2,3,40-20,20,40,38,4,#2AD572,https://images.fotmob.com/image_resources/logo...
4,Bundesliga,home,2025/2026,Hoffenheim,Hoffenheim,8226,/teams/8226/overview/hoffenheim,None,None,17,10,2,5,35-21,14,35,32,5,#0046A7,https://images.fotmob.com/image_resources/logo...

📌 Bundesliga — AWAY

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,idx,qualColor,logo
0,Bundesliga,away,2025/2026,Bayern München,Bayern München,9823,/teams/9823/overview/bayern-munchen,None,None,17,14,3,0,54-17,37,54,45,1,#2AD572,https://images.fotmob.com/image_resources/logo...
1,Bundesliga,away,2025/2026,Borussia Dortmund,Dortmund,9789,/teams/9789/overview/borussia-dortmund,None,None,17,9,5,3,30-18,12,30,32,2,#2AD572,https://images.fotmob.com/image_resources/logo...
2,Bundesliga,away,2025/2026,Hoffenheim,Hoffenheim,8226,/teams/8226/overview/hoffenheim,None,None,17,8,5,4,30-31,-1,30,29,3,#2AD572,https://images.fotmob.com/image_resources/logo...
3,Bundesliga,away,2025/2026,Bayer Leverkusen,Leverkusen,8178,/teams/8178/overview/bayer-leverkusen,None,None,17,8,4,5,30-28,2,30,28,4,#2AD572,https://images.fotmob.com/image_resources/logo...
4,Bundesliga,away,2025/2026,RB Leipzig,RB Leipzig,178475,/teams/178475/overview/rb-leipzig,None,None,17,8,3,6,26-27,-1,26,27,5,#0046A7,https://images.fotmob.com/image_resources/logo...

📌 Bundesliga — LAST5

,Liga,Tipo,Temporada,name,shortName,featuredInMatch,id,pageUrl,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,ongoing,idx,qualColor,logo
0,Bundesliga,last5,2025/2026,Bayern München,Bayern München,False,9823,/teams/9823/overview/bayern-munchen,5,4,1,0,17-9,8,17,13,None,1,#2AD572,https://images.fotmob.com/image_resources/logo...
1,Bundesliga,last5,2025/2026,Augsburg,Augsburg,False,8406,/teams/8406/overview/augsburg,5,3,1,1,9-8,1,9,10,None,2,#2AD572,https://images.fotmob.com/image_resources/logo...
2,Bundesliga,last5,2025/2026,Hoffenheim,Hoffenheim,False,8226,/teams/8226/overview/hoffenheim,5,3,1,1,8-9,-1,8,10,None,3,#2AD572,https://images.fotmob.com/image_resources/logo...
3,Bundesliga,last5,2025/2026,Borussia Dortmund,Dortmund,False,9789,/teams/9789/overview/borussia-dortmund,5,3,0,2,10-5,5,10,9,None,4,#2AD572,https://images.fotmob.com/image_resources/logo...
4,Bundesliga,last5,2025/2026,RB Leipzig,RB Leipzig,False,178475,/teams/178475/overview/rb-leipzig,5,3,0,2,10-11,-1,10,9,None,5,#0046A7,https://images.fotmob.com/image_resources/logo...

📌 Bundesliga — XG

,Liga,Tipo,Temporada,teamId,team,J,xG,xG_diff,xGA,xGA_diff,xPTS,xPTS_diff,pos_real,pos_xG,pos_diff,logo
0,Bundesliga,xG,2025/2026,9823,Bayern München,34,100.7408,21.2592,41.9527,-5.9527,78.542547,10.457453,1,1,0,https://images.fotmob.com/image_resources/logo...
1,Bundesliga,xG,2025/2026,9789,Borussia Dortmund,34,63.7943,6.2057,39.6963,-5.6963,61.142083,11.857917,2,2,0,https://images.fotmob.com/image_resources/logo...
2,Bundesliga,xG,2025/2026,8178,Bayer Leverkusen,34,65.7123,2.2877,46.1519,0.8481,58.724898,0.275102,3,3,3,https://images.fotmob.com/image_resources/logo...
3,Bundesliga,xG,2025/2026,178475,RB Leipzig,34,67.3558,-1.3558,51.1817,-4.1817,56.748567,8.251433,4,4,-1,https://images.fotmob.com/image_resources/logo...
4,Bundesliga,xG,2025/2026,10269,VfB Stuttgart,34,60.4254,10.5746,51.0007,-2.0007,54.744556,7.255444,5,5,-1,https://images.fotmob.com/image_resources/logo...

🏆 Ligue 1
  -> all: OK, columnas=['name', 'shortName', 'id', 'pageUrl', 'deduction', 'ongoing', 'played', 'wins', 'draws', 'losses', 'scoresStr', 'goalConDiff', 'pts', 'idx', 'qualColor', 'logo']
  -> home: OK, columnas=['name', 'shortName', 'id', 'pageUrl', 'deduction', 'ongoing', 'played', 'wins', 'draws', 'losses', 'scoresStr', 'goalConDiff', 'goalsScored', 'pts', 'idx', 'qualColor', 'logo']
  -> away: OK, columnas=['name', 'shortName', 'id', 'pageUrl', 'deduction', 'ongoing', 'played', 'wins', 'draws', 'losses', 'scoresStr', 'goalConDiff', 'goalsScored', 'pts', 'idx', 'qualColor', 'logo']
  -> last5: OK, columnas=['name', 'shortName', 'featuredInMatch', 'id', 'pageUrl', 'played', 'wins', 'draws', 'losses', 'scoresStr', 'goalConDiff', 'goalsScored', 'pts', 'ongoing', 'idx', 'qualColor', 'logo']
  -> xG: OK, columnas=['teamId', 'team', 'J', 'xG', 'xG_diff', 'xGA', 'xGA_diff', 'xPTS', 'xPTS_diff', 'pos_real', 'pos_xG', 'pos_diff', 'logo']

📌 Ligue 1 — ALL

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,pts,idx,qualColor,logo
0,Ligue 1,all,2025/2026,Paris Saint-Germain,PSG,9847,/teams/9847/overview/paris-saint-germain,None,None,34,24,4,6,74-29,45,76,1,#2AD572,https://images.fotmob.com/image_resources/logo...
1,Ligue 1,all,2025/2026,Lens,Lens,8588,/teams/8588/overview/lens,None,None,34,22,4,8,66-35,31,70,2,#2AD572,https://images.fotmob.com/image_resources/logo...
2,Ligue 1,all,2025/2026,Lille,Lille,8639,/teams/8639/overview/lille,None,None,34,18,7,9,52-37,15,61,3,#2AD572,https://images.fotmob.com/image_resources/logo...
3,Ligue 1,all,2025/2026,Lyon,Lyon,9748,/teams/9748/overview/lyon,None,None,34,18,6,10,53-40,13,60,4,#FFD908,https://images.fotmob.com/image_resources/logo...
4,Ligue 1,all,2025/2026,Marseille,Marseille,8592,/teams/8592/overview/marseille,None,None,34,18,5,11,63-45,18,59,5,#0046A7,https://images.fotmob.com/image_resources/logo...

📌 Ligue 1 — HOME

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,idx,qualColor,logo
0,Ligue 1,home,2025/2026,Lens,Lens,8588,/teams/8588/overview/lens,None,None,17,14,0,3,35-13,22,35,42,1,#2AD572,https://images.fotmob.com/image_resources/logo...
1,Ligue 1,home,2025/2026,Paris Saint-Germain,PSG,9847,/teams/9847/overview/paris-saint-germain,None,None,17,13,2,2,41-12,29,41,41,2,#2AD572,https://images.fotmob.com/image_resources/logo...
2,Ligue 1,home,2025/2026,Marseille,Marseille,8592,/teams/8592/overview/marseille,None,None,17,11,4,2,41-20,21,41,37,3,#2AD572,https://images.fotmob.com/image_resources/logo...
3,Ligue 1,home,2025/2026,Lyon,Lyon,9748,/teams/9748/overview/lyon,None,None,17,12,1,4,30-18,12,30,37,4,#FFD908,https://images.fotmob.com/image_resources/logo...
4,Ligue 1,home,2025/2026,Rennes,Rennes,9851,/teams/9851/overview/rennes,None,None,17,10,4,3,30-17,13,30,34,5,#0046A7,https://images.fotmob.com/image_resources/logo...

📌 Ligue 1 — AWAY

,Liga,Tipo,Temporada,name,shortName,id,pageUrl,deduction,ongoing,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,idx,qualColor,logo
0,Ligue 1,away,2025/2026,Paris Saint-Germain,PSG,9847,/teams/9847/overview/paris-saint-germain,None,None,17,11,2,4,33-17,16,33,35,1,#2AD572,https://images.fotmob.com/image_resources/logo...
1,Ligue 1,away,2025/2026,Lille,Lille,8639,/teams/8639/overview/lille,None,None,17,10,2,5,28-20,8,28,32,2,#2AD572,https://images.fotmob.com/image_resources/logo...
2,Ligue 1,away,2025/2026,Lens,Lens,8588,/teams/8588/overview/lens,None,None,17,8,4,5,31-22,9,31,28,3,#2AD572,https://images.fotmob.com/image_resources/logo...
3,Ligue 1,away,2025/2026,Rennes,Rennes,9851,/teams/9851/overview/rennes,None,None,17,7,4,6,29-33,-4,29,25,4,#FFD908,https://images.fotmob.com/image_resources/logo...
4,Ligue 1,away,2025/2026,Lyon,Lyon,9748,/teams/9748/overview/lyon,None,None,17,6,5,6,23-22,1,23,23,5,#0046A7,https://images.fotmob.com/image_resources/logo...

📌 Ligue 1 — LAST5

,Liga,Tipo,Temporada,name,shortName,featuredInMatch,id,pageUrl,played,wins,draws,losses,scoresStr,goalConDiff,goalsScored,pts,ongoing,idx,qualColor,logo
0,Ligue 1,last5,2025/2026,Paris Saint-Germain,PSG,False,9847,/teams/9847/overview/paris-saint-germain,5,3,1,1,9-4,5,9,10,None,1,#2AD572,https://images.fotmob.com/image_resources/logo...
1,Ligue 1,last5,2025/2026,Auxerre,Auxerre,False,8583,/teams/8583/overview/auxerre,5,3,1,1,11-7,4,11,10,None,2,#2AD572,https://images.fotmob.com/image_resources/logo...
2,Ligue 1,last5,2025/2026,Strasbourg,Strasbourg,False,9848,/teams/9848/overview/strasbourg,5,3,1,1,12-10,2,12,10,None,3,#2AD572,https://images.fotmob.com/image_resources/logo...
3,Ligue 1,last5,2025/2026,Paris FC,Paris FC,False,6379,/teams/6379/overview/paris-fc,5,3,0,2,10-5,5,10,9,None,4,#FFD908,https://images.fotmob.com/image_resources/logo...
4,Ligue 1,last5,2025/2026,Rennes,Rennes,False,9851,/teams/9851/overview/rennes,5,3,0,2,10-9,1,10,9,None,5,#0046A7,https://images.fotmob.com/image_resources/logo...

📌 Ligue 1 — XG

,Liga,Tipo,Temporada,teamId,team,J,xG,xG_diff,xGA,xGA_diff,xPTS,xPTS_diff,pos_real,pos_xG,pos_diff,logo
0,Ligue 1,xG,2025/2026,9847,Paris Saint-Germain,34,72.0950,1.9050,31.9307,-2.9307,72.438917,3.561083,1,1,0,https://images.fotmob.com/image_resources/logo...
1,Ligue 1,xG,2025/2026,8588,Lens,34,67.6513,-1.6513,43.6623,-8.6623,62.150667,7.849333,2,2,0,https://images.fotmob.com/image_resources/logo...
2,Ligue 1,xG,2025/2026,8639,Lille,34,55.2639,-3.2639,36.8764,0.1236,58.951657,2.048343,3,3,0,https://images.fotmob.com/image_resources/logo...
3,Ligue 1,xG,2025/2026,8592,Marseille,34,61.9146,1.0854,47.8447,-2.8447,56.682383,2.317617,4,4,1,https://images.fotmob.com/image_resources/logo...
4,Ligue 1,xG,2025/2026,9748,Lyon,34,53.4969,-0.4969,45.4152,-5.4152,52.527850,7.472150,5,5,-1,https://images.fotmob.com/image_resources/logo...

In [4]:
# Comprobar que los logos cargan correctamente

clasificaciones["Premier League"]["xG"][["team", "logo", "xG", "xGA", "xPTS"]].head()

,team,logo,xG,xGA,xPTS
0,Arsenal,https://images.fotmob.com/image_resources/logo...,65.5997,28.3025,77.824531
1,Manchester City,https://images.fotmob.com/image_resources/logo...,71.3303,44.1955,71.038303
2,Manchester United,https://images.fotmob.com/image_resources/logo...,65.4876,48.5707,62.288436
3,Liverpool,https://images.fotmob.com/image_resources/logo...,61.3487,47.4282,61.609077
4,Chelsea,https://images.fotmob.com/image_resources/logo...,66.5331,52.2635,60.007062